class LocationData {
  static const Map<String, List<String>> zones = {
    'East India': [
      'West Bengal',
      'Odisha',
      'Bihar',
      'Jharkhand',
      'Andaman & Nicobar'
    ],
    'West India': [
      'Maharashtra',
      'Gujarat',
      'Goa',
      'Dadra & Nagar Haveli',
      'Daman & Diu'
    ],
    'North India': [
      'Punjab',
      'Chandigarh',
      'Haryana',
      'Uttar Pradesh',
      'Uttarakhand',
      'New Delhi',
      'Jammu & Kashmir',
      'Rajasthan',
      'Himachal Pradesh'
    ],
    'South India': [
      'Andhra Pradesh',
      'Karnataka',
      'Tamil Nadu',
      'Kerala',
      'Lakshadweep',
      "Pondicherry"
    ],
    'Central India': [
      'Chhatisgarh',
      'Madhya Pradesh',
    ],
    'North East India': [
      'Assam',
      'Tripura',
      'Nagaland',
      "Arunachal Pradesh",
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Sikkim'
    ],
  };

  static const Map<String, List<String>> states = {
    // East Zone
    'West Bengal': [
      'Adra',
      'Ahmadpur',
      'Aiho',
      'Aistala',
      'Alipurduar',
      'AlipurduarRlyJnc',
      'Alpur',
      'Amkula',
      'Amodghata',
      'Amtala',
      'Andul',
      'Anksa',
      'Ankurhati',
      'AnupNagar',
      'Arambag',
      'Argari',
      'Arra',
      'Asansol',
      'AshoknagarKalyangarh',
      'Aurangabad',
      'BablariDewanganj',
      'Badhagachhi',
      'Baduria',
      'Bagnan',
      'BaharamPur',
      'Bahirgram',
      'Bahula',
      'Baidyabati',
      'Bairatisal',
      'BalaramPota',
      'Balarampur',
      'Balichak',
      'Ballavpur',
      'Bally',
      'Balurghat',
      'Bamunari',
      'BanarhatTeaGarden',
      'Bangaon',
      'Bankra',
      'Bankura',
      'Bansberia',
      'Banshra',
      'Banupur',
      'BaraBamonia',
      'Barabazar',
      'Baranagar',
      'Barasat',
      'Barddhaman',
      'Barijhati',
      'Barjora',
      'Barrackpur',
      'BarrackpurCantonment',
      'Baruihuda',
      'Baruipur',
      'Basirhat',
      'Baska',
      'Begampur',
      'Beldanga',
      'Beldubi',
      'Belebathan',
      'Beliatore',
      'Bhadreswar',
      'Bhandardaha',
      'BhangarRaghunathpur',
      'BhangriPrathamKhanda',
      'Bhanowara',
      'Bhatpara',
      'BholarDabri',
      'BidhanNagar',
      'Bikihakola',
      'Bilandapur',
      'Bilpahari',
      'BipraNoapara',
      'Birlapur',
      'Birnagar',
      'Bishnupur',
      'Bolpur',
      'Bowali',
      'BudgeBudge',
      'CartRoad',
      'Chachanda',
      'ChakBankola',
      'ChakBansberia',
      'ChakEnayetnagar',
      'ChakKashipur',
      'Chakapara',
      'Chakdaha',
      'Champdani',
      'Chamrail',
      'Chandannagar',
      'Chandpur',
      'Chandrakona',
      'Chapari',
      'Chapui',
      'CharBrahmanagar',
      'CharMaijdia',
      'Charka',
      'ChataKalikapur',
      'Chechakhata',
      'Chelad',
      'Chhora',
      'Chikrand',
      'Chittaranjan',
      'Contai',
      'Dafahat',
      'Dainhat',
      'DakshinBaguan',
      'DakshinJhapardaha',
      'DakshinRajyadharpur',
      'Dalkhola',
      'Dalurband',
      'Darappur',
      'Darjiling',
      'Debipur',
      'Deuli',
      'Dhakuria',
      'Dhandadihi',
      'Dhanyakuria',
      'Dharmapur',
      'Dhatrigram',
      'Dhuliya',
      'Dhulian',
      'Dhupguri',
      'Dhusaripara',
      'DiamondHarbour',
      'Dignala',
      'Dinhata',
      'Domjur',
      'Dubrajpur',
      'Dumdum',
      'Durgapur',
      'Durlabhganj',
      'Egra',
      'Eksara',
      'EnglishBazar',
      'Falakata',
      'FarrakkaBarrageTownship',
      'Fatellapur',
      'Gabberia',
      'Gairkata',
      'Gangarampur',
      'Garalgachha',
      'GarshyamNagar',
      'Garulia',
      'Gayespur',
      'Ghatal',
      'Gharsala',
      'Goaljan',
      'Goasafat',
      'Gobardanga',
      'Gopalpur',
      'Gopinathpur',
      'GoraBazar',
      'Guma',
      'Guriahati',
      'Guskara',
      'Habra',
      'Haldia',
      'Haldibari',
      'Halisahar',
      'Haora',
      'HarhariaChak',
      'Haripur',
      'Harishpur',
      'Hatgachha',
      'Hatsimla',
      'Hijuli',
      'HindusthanCablesTown',
      'HugliChinsurah',
      'IchhapurDefenceEstate',
      'Islampur',
      'Jafarpur',
      'Jagadanandapur',
      'Jagadishpur',
      'Jagataj',
      'JalaKendua',
      'Jalpaiguri',
      'Jamuria',
      'Jangipur',
      'Jaygaon',
      'JaynagarMazilpur',
      'Jemari',
      'JemariJKNagarTownship',
      'Jetia',
      'Jhalda',
      'Jhargram',
      'Jhorhat',
      'JiaganjAzimganj',
      'JotKamal',
      'KachuPukur',
      'Kajora',
      'Kakdihi',
      'Kalara',
      'Kaliaganj',
      'Kalimpong',
      'Kalna',
      'Kalyani',
      'Kamarhati',
      'Kanaipur',
      'Kanchrapara',
      'Kandi',
      'Kankuria',
      'Kantlia',
      'Kanyanagar',
      'Karimpur',
      'Kasba',
      'KasimBazar',
      'Katwa',
      'Kaugachhi',
      'Kenda',
      'KendraKhottamdi',
      'Kendua',
      'Kesabpur',
      'Khagrabari',
      'Khalia',
      'Khalor',
      'Khandra',
      'Khantora',
      'Kharagpur',
      'KharagpurRlySettlement',
      'Kharar',
      'Khardaha',
      'KharimalaKhagrabari',
      'Kharsarai',
      'Khodarampur',
      'KochBihar',
      'Kodalia',
      'Kolaghat',
      'Kolkata',
      'Konardihi',
      'Konnagar',
      'Krishnanagar',
      'Krishnapur',
      'Kshidirpur',
      'Kshirpai',
      'Kulihanda',
      'Kulti',
      'Kunustara',
      'Kurseong',
      'Madanpur',
      'Madhusudanpur',
      'Madhyamgram',
      'Maheshtala',
      'Mahiari',
      'Mahira',
      'Mainaguri',
      'Makardaha',
      'Mal',
      'Mandarbani',
      'Manikpur',
      'Mansinhapur',
      'Maslandapur',
      'Mathabhanga',
      'Medinipur',
      'Mekliganj',
      'Memari',
      'Mirik',
      'Monoharpur',
      'Mrigala',
      'Muragachha',
      'Murgathaul',
      'Murshidabad',
      'Nabadwip',
      'Nabagram',
      'NabagramColony',
      'Nabgram',
      'NachhratpurKatabari',
      'Naihati',
      'Nasra',
      'Natibpur',
      'Naupala',
      'NebadhaiDuttapukur',
      'NewBarrackpur',
      'Nibra',
      'Nokpul',
      'NorthBarrackpur',
      'NorthDumdum',
      'OldMaldah',
      'Ondal',
      'Pairagachha',
      'Palashban',
      'Panchla',
      'Panchpara',
      'Pandua',
      'PangachhiyaB',
      'Paniara',
      'Panihati',
      'Panuhat',
      'ParBeliya',
      'Parashkol',
      'Parasia',
      'Parbbatipur',
      'PaschimJitpur',
      'PaschimPunropara',
      'PattabongTeaGarden',
      'Patuli',
      'Patulia',
      'Phulia',
      'Podara',
      'Prayagpur',
      'Pujali',
      'PurbaTajpur',
      'Puruliya',
      'Raghudebbati',
      'Raghunathchak',
      'Raghunathpur',
      'RaghunathpurPsDankuni',
      'RaghunathpurPsMagra',
      'Raigachhi',
      'Raiganj',
      'RajarhatGopalpur',
      'RajpurSonarpur',
      'Ramchandrapur',
      'Ramjibanpur',
      'Ramnagar',
      'Rampurhat',
      'Ranaghat',
      'Raniganj',
      'Ratibati',
      'Rishra',
      'Ruiya',
      'STPowerProjectTown',
      'Sadpur',
      'Sahajadpur',
      'Sahapur',
      'Sainthia',
      'Salap',
      'Sankarpur',
      'Sankrail',
      'Santipur',
      'Santoshpur',
      'Sarenga',
      'Sarpi',
      'Satigachha',
      'Serampore',
      'Serpur',
      'Shankhanagar',
      'Siduli',
      'Siliguri',
      'Simla',
      'Singur',
      'Sirsha',
      'Sobhaganj',
      'Sonamukhi',
      'Sonatikiri',
      'SouthDumdum',
      'Srikantabati',
      'Srirampur',
      'Sukdal',
      'Suri',
      'Taherpur',
      'Taki',
      'Talbandha',
      'Tamluk',
      'Tarakeswar',
      'Tentulkuli',
      'Titagarh',
      'Tufanganj',
      'Ukhra',
      'Uluberia',
      'UttarBagdogra',
      'UttarDurgapur',
      'UttarGoara',
      'UttarKalas',
      'UttarKamakhyaguri',
      'UttarLatabari',
      'UttarMahammadpur',
      'Uttar Pirpur',
      'Uttar Raypur',
      'Uttarpara Kotrung'
    ],
    'Andaman & Nicobar': ['Bombooflat', 'Garacharma', 'PortBlair'],
    'Odisha': [
      'Adityapur',
      'Amlabad',
      'Angarpathar',
      'Ara',
      'BabuaKalan',
      'Bagbera',
      'Baliari',
      'Balkundra',
      'Bandhgora',
      'Barajamda',
      'Barhi',
      'Barkakana',
      'Barughutu',
      'Barwadih',
      'Basaria',
      'Basukinath',
      'Bermo',
      'Bhagatdih',
      'Bhojudih',
      'Bhowrah',
      'Bhuli',
      'Bokaro',
      'BokaroSteelCity',
      'Bundu',
      'Chaibasa',
      'Chakradharpur',
      'Chakulia',
      'ChandaUr',
      'Chandil',
      'Chandrapura',
      'Chas',
      'Chatra',
      'Chhatatanr',
      'ChhotaGobindpur',
      'Chhotaputki',
      'Chiria',
      'Chirkunda',
      'Churi',
      'Daltonganj',
      'Danguwapasi',
      'Dari',
      'Deoghar',
      'Deorikalan',
      'Dhanbad',
      'Dhanwar',
      'Dhaunsar',
      'Dugda',
      'Dumarkunda',
      'Dumka',
      'Egarkunr',
      'Gadhra',
      'Garhwa',
      'Ghatshila',
      'Ghorabandha',
      'Gidi',
      'Giridih',
      'Gobindpur',
      'Godda',
      'Godhar',
      'Gomoh',
      'Gua',
      'Gumia',
      'Gumla',
      'Haludbani',
      'Hazaribag',
      'Hesla',
      'Hussainabad',
      'Isri',
      'Jadugora',
      'Jamadoba',
      'Jamshedpur',
      'Jamtara',
      'JaridihBazar',
      'Jasidih',
      'Jena',
      'Jharia',
      'JhariaKhas',
      'Jhinkpani',
      'JhumriTilaiya',
      'Jorapokhar',
      'Jugsalai',
      'Kailudih',
      'Kalikapur',
      'Kandra',
      'Kanke',
      'Katras',
      'Kedla',
      'Kenduadih',
      'Kharkhari',
      'Kharsawan',
      'Khelari',
      'Khunti',
      'Kiriburu',
      'Kodarma',
      'Kuju',
      'Kurpania',
      'Kustai',
      'Lakarka',
      'Lapanga',
      'Latehar',
      'Lohardaga',
      'Loyabad',
      'Madhupur',
      'Maithon',
      'Malkera',
      'Mango',
      'Marma',
      'MeghahatuburuForestVillage',
      'Mera',
      'Meru',
      'Mihijam',
      'Mugma',
      'Muri',
      'Musabani',
      'NagriKalan',
      'Nirsa',
      'Noamundi',
      'OkniNoIi',
      'Orla',
      'Pakaur',
      'Palawa',
      'Panchet',
      'Paratdih',
      'Pathardih',
      'Patratu',
      'Phusro',
      'PondarKanali',
      'Rajmahal',
      'RamgarhCantonment',
      'Ranchi',
      'ReligaraAliasPachhiari',
      'Rohraband',
      'Sahibganj',
      'Sahnidih',
      'Saraidhela',
      'Sarjamda',
      'Saunda',
      'Seraikela',
      'Sewai',
      'Sijhua',
      'Sijua',
      'Simdega',
      'Sindri',
      'Sinduria',
      'Sini',
      'Sirka',
      'Siuliban',
      'Tati',
      'TenuDamCumKathhara',
      'Tisra',
      'Topa',
      'Topchanchi',
      'Umarkote',
    ],
    'Bihar': [
      'Amarpur',
      'Araria',
      'Areraj',
      'Ara',
      'Asarganj',
      'Aurangabad',
      'Bagaha',
      'Bahadurganj',
      'Bairgania',
      'Bakhtiarpur',
      'Banka',
      'BanmankhiBazar',
      'Barahiya',
      'Barauli',
      'BarauniIocTownship',
      'Barbigha',
      'Barh',
      'Begusarai',
      'Behea',
      'Belsand',
      'Bettiah',
      'Bhabua',
      'BhagalpurMCorp',
      'Bihar',
      'Bikramganj',
      'Birpur',
      'BodhGaya',
      'Buxar',
      'Chakia',
      'Chanpatia',
      'Chapra',
      'Colgong',
      'Dalsinghsarai',
      'Darbhanga',
      'Daudnagar',
      'Dehri',
      'Dhaka',
      'Dighwara',
      'DinapurCantt',
      'DinapurNizamat',
      'Dumra',
      'Dumraon',
      'Fatwah',
      'Forbesganj',
      'Gaya',
      'Ghoghardiha',
      'GogriJamalpur',
      'Gopalganj',
      'Habibpur',
      'Hajipur',
      'Hilsa',
      'Hisua',
      'Islampur',
      'Jagdishpur',
      'Jainagar',
      'Jamalpur',
      'Jamhaur',
      'Jamui',
      'JanakpurRoad',
      'Jehanabad',
      'Jhajha',
      'Jhanjharpur',
      'Jogbani',
      'Kanti',
      'Kasba',
      'Kataiya',
      'Katihar',
      'Khagaria',
      'Khagaul',
      'Kharagpur',
      'Khusrupur',
      'Kishanganj',
      'Koath',
      'Koilwar',
      'Lakhisarai',
      'Lalganj',
      'Lauthaha',
      'Madhepura',
      'Madhubani',
      'Maharajganj',
      'MahnarBazar',
      'Mairwa',
      'Makhdumpur',
      'Maner',
      'Manihari',
      'Marhaura',
      'MasaUarhi',
      'Mirganj',
      'Mohiuddinagar',
      'Mokameh',
      'Motihari',
      'Motipur',
      'Munger',
      'Murliganj',
      'Muzaffarpur',
      'Nabinagar',
      'Narkatiaganj',
      'Naugachhia',
      'Nawada',
      'Nirmali',
      'Nokha',
      'Paharpur',
      'Patna',
      'PhulwariSharif',
      'Piro',
      'Purnia',
      'Rafiganj',
      'Raghunathpur',
      'Rajgir',
      'Ramnagar',
      'RaxaulBazar',
      'Revelganj',
      'Rosera',
      'Saharsa',
      'Samastipur',
      'Sasaram',
      'Shahpur',
      'Sheikhpura',
      'Sheohar',
      'Sherghati',
      'Silao',
      'Sitamarhi',
      'Siwan',
      'Sonepur',
      'Sugauli',
      'Sultanganj',
      'Supaul',
      'Tekari',
      'Thakurganj',
      'Warisaliganj'
    ],
    'Jharkhand': [
      'Adityapur',
      'Amlabad',
      'Angarpathar',
      'Ara',
      'BabuaKalan',
      'Bagbera',
      'Baliari',
      'Balkundra',
      'Bandhgora',
      'Barajamda',
      'Barhi',
      'Barkakana',
      'Barughutu',
      'Barwadih',
      'Basaria',
      'Basukinath',
      'Bermo',
      'Bhagatdih',
      'Bhojudih',
      'Bhowrah',
      'Bhuli',
      'Bokaro',
      'BokaroSteelCity',
      'Bundu',
      'Chaibasa',
      'Chakradharpur',
      'Chakulia',
      'ChandaUr',
      'Chandil',
      'Chandrapura',
      'Chas',
      'Chatra',
      'Chhatatanr',
      'ChhotaGobindpur',
      'Chhotaputki',
      'Chiria',
      'Chirkunda',
      'Churi',
      'Daltonganj',
      'Danguwapasi',
      'Dari',
      'Deoghar',
      'Deorikalan',
      'Dhanbad',
      'Dhanwar',
      'Dhaunsar',
      'Dugda',
      'Dumarkunda',
      'Dumka',
      'Egarkunr',
      'Gadhra',
      'Garhwa',
      'Ghatshila',
      'Ghorabandha',
      'Gidi',
      'Giridih',
      'Gobindpur',
      'Godda',
      'Godhar',
      'Gomoh',
      'Gua',
      'Gumia',
      'Gumla',
      'Haludbani',
      'Hazaribag',
      'Hesla',
      'Hussainabad',
      'Isri',
      'Jadugora',
      'Jamadoba',
      'Jamshedpur',
      'Jamtara',
      'JaridihBazar',
      'Jasidih',
      'Jena',
      'Jharia',
      'JhariaKhas',
      'Jhinkpani',
      'JhumriTilaiya',
      'Jorapokhar',
      'Jugsalai',
      'Kailudih',
      'Kalikapur',
      'Kandra',
      'Kanke',
      'Katras',
      'Kedla',
      'Kenduadih',
      'Kharkhari',
      'Kharsawan',
      'Khelari',
      'Khunti',
      'Kiriburu',
      'Kodarma',
      'Kuju',
      'Kurpania',
      'Kustai',
      'Lakarka',
      'Lapanga',
      'Latehar',
      'Lohardaga',
      'Loyabad',
      'Madhupur',
      'Maithon',
      'Malkera',
      'Mango',
      'Marma',
      'MeghahatuburuForestVillage',
      'Mera',
      'Meru',
      'Mihijam',
      'Mugma',
      'Muri',
      'Musabani',
      'NagriKalan',
      'Nirsa',
      'Noamundi',
      'OkniNoIi',
      'Orla',
      'Pakaur',
      'Palawa',
      'Panchet',
      'Paratdih',
      'Pathardih',
      'Patratu',
      'Phusro',
      'PondarKanali',
      'Rajmahal',
      'RamgarhCantonment',
      'Ranchi',
      'ReligaraAliasPachhiari',
      'Rohraband',
      'Sahibganj',
      'Sahnidih',
      'Saraidhela',
      'Sarjamda',
      'Saunda',
      'Seraikela',
      'Sewai',
      'Sijhua',
      'Sijua',
      'Simdega',
      'Sindri',
      'Sinduria',
      'Sini',
      'Sirka',
      'Siuliban',
      'Tati',
      'TenuDamCumKathhara',
      'Tisra',
      'Topa',
      'Topchanchi'
    ],

    // West Zone
    'Maharashtra': [
      'Achalpur',
      'Ahmadnagar',
      'Ahmadnagar',
      'Ahmadpur',
      'Ajra',
      'Akkalkot',
      'Akola',
      'Akot',
      'Alandi',
      'Alibag',
      'Amalner',
      'Ambad',
      'Ambarnath',
      'Ambejogai',
      'Ambivali Tarf Wankhal',
      'Amravati',
      'Anjangaon',
      'Arvi',
      'Ashta',
      'Aurangabad',
      'Aurangabad',
      'Ausa',
      'Babhulgaon',
      'Badlapur',
      'Balapur',
      'Ballarpur',
      'Baramati',
      'Barshi',
      'Basmath',
      'Bhadravati',
      'Bhagur',
      'Bhandara',
      'Bhingar',
      'Bhiwandi',
      'Bhokardan',
      'Bhor',
      'Bhum',
      'Bhusawal',
      'Bid',
      'Biloli',
      'Birwadi',
      'Boisar',
      'Brahmapuri',
      'Budhgaon',
      'Buldana',
      'Chakan',
      'Chalisgaon',
      'Chandrapur',
      'Chandur',
      'Chandur',
      'Chandurbazar',
      'Chicholi',
      'Chikhaldara',
      'Chikhli',
      'Chinchani',
      'Chiplun',
      'Chopda',
      'Dahanu',
      'Dapoli Camp',
      'Darwha',
      'Daryapur Banosa',
      'Dattapur Dhamangaon',
      'Daund',
      'Davlameti',
      'Deglur',
      'Dehu',
      'Dehu Road',
      'Deolali',
      'Deolali Pravara',
      'Deoli',
      'Desaiganj',
      'Deulgaon Raja',
      'Dewhadi',
      'Dharangaon',
      'Dharmabad',
      'Dharur',
      'Dhatau',
      'Dhule',
      'Digdoh',
      'Digras',
      'Dondaicha-warwade',
      'Dudhani',
      'Durgapur',
      'Dyane',
      'Eklahare',
      'Erandol',
      'Faizpur',
      'Gadchiroli',
      'Gadhinglaj',
      'Gandhinagar',
      'Ganeshpur',
      'Gangakhed',
      'Gangapur',
      'Georai',
      'Ghatanji',
      'Ghoti Budruk',
      'Ghugus',
      'Ghulewadi',
      'Godoli',
      'Gokhivare',
      'Gondiya',
      'Goregaon',
      'Greater Mumbai',
      'Guhagar',
      'Hadgaon',
      'Hinganghat',
      'Hingoli',
      'Hupari',
      'Ichalkaranji',
      'Igatpuri',
      'Indapur',
      'Jalgaon',
      'Jalgaon',
      'Jalgaon (Jamod)',
      'Jalna',
      'Jamkhed',
      'Jawhar',
      'Jaysingpur',
      'Jejuri',
      'Jintur',
      'Junnar',
      'Kabnur',
      'Kagal',
      'Kalamb',
      'Kalambe Turf Thane',
      'Kalameshwar',
      'Kalamnuri',
      'Kalundre',
      'Kalyan-dombivali',
      'Kamptee',
      'Kamptee',
      'Kandari',
      'Kandhar',
      'Kandri',
      'Kandri',
      'Kanhan (Pipri)',
      'Kankavli',
      'Kannad',
      'Karad',
      'Karanja',
      'Karanje Turf Satara',
      'Karivali',
      'Karjat',
      'Karmala',
      'Kasara Budruk',
      'Katai',
      'Katkar',
      'Katol',
      'Kegaon',
      'Khadkale',
      'Khamgaon',
      'Khapa',
      'Khed',
      'Khed',
      'Kherdi',
      'Khoni',
      'Khopoli',
      'Khuldabad',
      'Kinwat',
      'Kirkee',
      'Kodoli',
      'Kolhapur',
      'Kon',
      'Kondumal',
      'Kopargaon',
      'Kopharad',
      'Korocho',
      'Kudal',
      'Kundalwadi',
      'Kurduvadi',
      'Kurundvad',
      'Kusgaon Budruk',
      'Lanja',
      'Lasalgaon',
      'Latur',
      'Loha',
      'Lonar',
      'Lonavala',
      'Madhavnagar',
      'Mahabaleshwar',
      'Mahad',
      'Mahadula',
      'Maindargi',
      'Malegaon',
      'Malkapur',
      'Malkapur',
      'Malkapur',
      'Malwan',
      'Manadur',
      'Manchar',
      'Mangalvedhe',
      'Mangrulpir',
      'Manjlegaon',
      'Manmad',
      'Manor',
      'Mansar',
      'Manwath',
      'Matheran',
      'Mehkar',
      'Mhasla',
      'Mhaswad',
      'Mira-bhayandar',
      'Mohpa',
      'Mohpada Alias Wasambe',
      'Morshi',
      'Mowad',
      'Mudkhed',
      'Mukhed',
      'Mul',
      'Murbad',
      'Murgud',
      'Murtijapur',
      'Murud',
      'Murum',
      'Nachane',
      'Nagapur',
      'Nagardeole',
      'Nagothana',
      'Nagpur',
      'Nakoda',
      'Nala Sopara',
      'Naldurg',
      'Nanded-waghala',
      'Nandgaon',
      'Nandura',
      'Nandurbar',
      'Narkhed',
      'Nashik',
      'Navghar-manikpur',
      'Navi Mumbai',
      'Navi Mumbai (Panvel, Raigarh)',
      'Nawapur',
      'Neral',
      'Nilanga',
      'Nildoh',
      'Nimbhore Budruk',
      'Osmanabad',
      'Ozar',
      'Pachgaon',
      'Pachora',
      'Padagha',
      'Paithan',
      'Palghar',
      'Pali',
      'Panchgani',
      'Pandharkaoda',
      'Pandharpur',
      'Pandharpur',
      'Panhala',
      'Panvel',
      'Paranda',
      'Parbhani',
      'Parli',
      'Parola',
      'Partur',
      'Pasthal',
      'Patan',
      'Pathardi',
      'Pathri',
      'Patur',
      'Pauni',
      'Pen',
      'Peth Umri',
      'Phaltan',
      'Pimpri Chinchwad',
      'Poladpur',
      'Pulgaon',
      'Pune',
      'Pune',
      'Purna',
      'Purushottamnagar',
      'Pusad',
      'Rahimatpur',
      'Rahta Pimplas',
      'Rahuri',
      'Rajapur',
      'Rajgurunagar (Khed)',
      'Rajur',
      'Rajura',
      'Ramtek',
      'Ratnagiri',
      'Raver',
      'Risod',
      'Roha Ashtami',
      'Sailu',
      'Sandor',
      'Sangamner',
      'Sangli-miraj & Kupwad',
      'Sangole',
      'Sasti',
      'Sasvad',
      'Satana',
      'Satara',
      'Savda',
      'Savner',
      'Sawantwadi',
      'Sawari Jawharnagar',
      'Shahade',
      'Shahapur',
      'Shegaon',
      'Shelar',
      'Shendurjana',
      'Shirdi',
      'Shirpur-warwade',
      'Shirur',
      'Shirwal',
      'Shivajinagar',
      'Shivatkar (Nira)',
      'Shrigonda',
      'Shrirampur',
      'Shrirampur(rural)',
      'Shrivardhan',
      'Sillewada',
      'Sillod',
      'Sindi',
      'Sindi Turf Hindnagar',
      'Sindkhed Raja',
      'Singnapur',
      'Sinnar',
      'Solapur',
      'Sonegaon (Nipani)',
      'Sonpeth',
      'Soyagaon',
      'Surgana',
      'Talegaon Dabhade',
      'Talode',
      'Taloje Panchnad',
      'Tarapur',
      'Tasgaon',
      'Tathavade',
      'Tekadi',
      'Telhara',
      'Thane',
      'Tirora',
      'Totaladoh',
      'Trimbak',
      'Tuljapur',
      'Tumsar',
      'Uchgaon',
      'Udgir',
      'Ulhasnagar',
      'Umarga',
      'Umarkhed',
      'Umarsara',
      'Umbar Pada Nandade',
      'Umred',
      'Umri Pragane Balapur',
      'Uran',
      'Uran Islampur',
      'Utekhol',
      'Vada',
      'Vadgaon',
      'Vadgaon Kasba',
      'Vaijapur',
      'Vanvadi (Sadashivgad)',
      'Vasai',
      'Vasantnagar',
      'Vashind',
      'Vengurla',
      'Virar',
      'Vita',
      'Wadgaon Road',
      'Wadi',
      'Waghapur',
      'Wai',
      'Wajegaon',
      'Walani',
      'Waliv',
      'Wanadongri',
      'Wani',
      'Wardha',
      'Warora',
      'Warud',
      'Washim',
      'Yavatmal',
      'Yawal',
      'Yerkheda',
      'Yevla'
    ],

    'Gujarat': [
      'Aadityana',
      'Aambaliyasan',
      'Aantaliya',
      'Aarambhada',
      'Abrama',
      'Adalaj',
      'Ahmedabad',
      'Ahmedabad Cantonment',
      'Alang',
      'Ambaji',
      'Amreli',
      'Anand',
      'Andada',
      'Anjar',
      'Anklav',
      'Anklesvar',
      'Anklesvar Ina',
      'Atul',
      'Bagasara',
      'Bajva',
      'Balasinor',
      'Bantwa',
      'Bardoli',
      'Bavla',
      'Bedi',
      'Bhachau',
      'Bhanvad',
      'Bharuch',
      'Bharuch Ina',
      'Bhavnagar',
      'Bhayavadar',
      'Bhuj',
      'Bilimora',
      'Bodeli',
      'Bopal',
      'Boriavi',
      'Borsad',
      'Botad',
      'Chaklasi',
      'Chala',
      'Chalala',
      'Chalthan',
      'Chanasma',
      'Chandkheda',
      'Chandlodiya',
      'Chanod',
      'Chhaprabhatha',
      'Chhattral Ina',
      'Chhaya',
      'Chhota Udaipur',
      'Chikhli',
      'Chiloda(Naroda)',
      'Chorvad',
      'Dabhoi',
      'Dahegam',
      'Dakor',
      'Damnagari',
      'Deesa',
      'Devgadbaria',
      'DevSar',
      'Dhandhuka',
      'Dhanera',
      'Dharampur',
      'Dhola',
      'Dholka',
      'Dhoraji',
      'Dhrangadhra',
      'Dhrol',
      'Digvijaygram',
      'Dohad',
      'Dungra',
      'Dwarka',
      'Freelandgunj',
      'Gadhada',
      'Gandevi',
      'Gandhidham',
      'Gandhinagar',
      'Gariadhar',
      'Ghatlodiya',
      'Ghogha',
      'Godhra',
      'Gondal',
      'Gota',
      'Gsfc Complex Ina',
      'Hajira Ina',
      'Halol',
      'Halvad',
      'Harij',
      'Himatnagar',
      'Ichchhapor',
      'Idar',
      'Jafrabad',
      'Jalalpor',
      'Jam Jodhpur',
      'Jambusar',
      'Jamnagar',
      'Jasdan',
      'Jawaharnagar (Gujarat Refinery)',
      'Jetpur Navagadh',
      'Jodhpur',
      'Joshapura',
      'Junagadh',
      'Kadi',
      'Kadodara',
      'Kalavad',
      'Kali',
      'Kalol',
      'Kalol Ina',
      'Kandla',
      'Kanodar',
      'Kapadvanj',
      'Karachiya',
      'Karmsad',
      'Karjan',
      'Katpar',
      'Keshod',
      'Kevadiya',
      'Khambhalia',
      'Khambhat',
      'Kharaghoda',
      'Kheda',
      'Khedbrahma',
      'Kheralu',
      'Kodinar',
      'Kosamba',
      'Kutiyana',
      'Lambha',
      'Lathi',
      'Limdhi',
      'Limla',
      'Lunawada',
      'Mahmedavad',
      'Mahesana',
      'Mahudha',
      'Mahuva',
      'Mahuwar',
      'Makarba',
      'Maktampur',
      'Malpur',
      'Manavadar',
      'Mandvi',
      'Mangrol',
      'Mansa',
      'Meghraj',
      'Memnagar',
      'Mithapur',
      'Modasa',
      'Mogravadi',
      'Morvi',
      'Motera',
      'Mundra',
      'Nadiad',
      'Nanakvada',
      'Nandej',
      'Nandesari',
      'Nandesari Ina',
      'Navagamghed',
      'Navsari',
      'Ode',
      'Okha Port',
      'Paddhari',
      'Padra',
      'Palanpur',
      'Palej',
      'Palitana',
      'Pardi',
      'Parnera',
      'Parvat',
      'Patan',
      'Petlad',
      'Petro Chemical Complex Ina',
      'Porbandar',
      'Prantij',
      'Radhanpur',
      'Rajkot',
      'Rajpipla',
      'Rajula',
      'Ramol',
      'Ranavav',
      'Ranip',
      'Ranoli',
      'Rapar',
      'Sachin',
      'Sachin Ina',
      'Salaya',
      'Sanand',
      'Santrampur',
      'Sarigam Ina',
      'Sarkhej-Okaf',
      'Savarkundla',
      'Sayan',
      'Sidhpur',
      'Sihor',
      'Sikka',
      'Singarva',
      'Songadh',
      'Surajkaradi',
      'Surat',
      'Surendranagar Dudhrej',
      'Talaja',
      'Talod',
      'Tarsali',
      'Thaltej',
      'Thangadh',
      'Tharad',
      'Ukkai',
      'Umbergaon',
      'Umbergaon Ina',
      'Umreth',
      'Un',
      'Una',
      'Unjha',
      'Upleta',
      'Utran',
      'Vadia',
      'Vadnagar',
      'Vadodara',
      'Vaghodia Ina',
      'Vallabh Vidhyanagar',
      'Valsad',
      'Valsad Ina',
      'Vanthali',
      'Vapi',
      'Vapi Ina',
      'Vartej',
      'Vasna Borsad Ina',
      'Vastral',
      'Vastrapur',
      'Vejalpur',
      'Veraval',
      'Vijalpor',
      'Vijapur',
      'Viramgam',
      'Visavadar',
      'Visnagar',
      'Vitthal Udyognagar Ina',
      'Vyara',
      'Wadhwan',
      'Wankaner',
      'Zalod'
    ],

    'Goa': [
      'Aldona',
      'Aquem',
      'Bambolim',
      'Bandora',
      'Benaulim',
      'Bicholim',
      'Calangute',
      'Calapor',
      'Canacona',
      'Candolim',
      'Carapur',
      'Chicalim',
      'Chimbel',
      'Chinchinim',
      'Colvale',
      'Cuncolim',
      'Curchorem Cacora',
      'Curti',
      'Davorlim',
      'Goa Velha',
      'Guirim',
      'Mapusa',
      'Margao',
      'Mormugao',
      'Navelim',
      'Pale',
      'Panaji',
      'Parcem',
      'Penha-de-franca',
      'Pernem',
      'Ponda',
      'Quepem',
      'Queula',
      'Reis Magos',
      'Saligao',
      'Sancoale',
      'Sanguem',
      'Sanquelim',
      'Sanvordem',
      'Sao Jose-de-areal',
      'Siolim',
      'Socorro (Serula)',
      'Valpoi',
      'Varca'
    ],

    'Dadra & Nagar Haveli': ['Amli', 'Silvassa'],

    'Daman & Diu': ['Daman', 'Diu'],

    // North Zone
    'Chandigarh': ['Chandigarh'],

    'Punjab': [
      'Abohar',
      'Adampur',
      'Ahmedgarh',
      'Ajnala',
      'Akalgarh',
      'Alawalpur',
      'Amloh',
      'Amritsar',
      'Amritsar Cantt.',
      'Anandpur Sahib',
      'Badhni Kalan',
      'Bagha Purana',
      'Balachaur',
      'Banaur',
      'Banga',
      'Baretta',
      'Bariwala',
      'Barnala',
      'Bassi Pathana',
      'Batala',
      'Bathinda',
      'Begowal',
      'Bhabat',
      'Bhadaur',
      'Bhankharpur',
      'Bharoli Kalan',
      'Bhawanigarh',
      'Bhikhi',
      'Bhikhiwind',
      'Bhissiana',
      'Bhogpur',
      'Buch Mandi',
      'Bhulath',
      'Budha Theh',
      'Budhlada',
      'Cheema',
      'Chohal',
      'Daroha',
      'Dasua',
      'Daulatpur',
      'Dera Baba Nanak',
      'Dera Bassi',
      'Dhanaula',
      'Dharamkot',
      'Dhariwal',
      'Dhilwan',
      'Dhuri',
      'Dina Nagar',
      'Dirba',
      'Faridkot',
      'Fatehgarh Churian',
      'Fazilka',
      'Firozpur',
      'Firozpur Cantt.',
      'Gardhiwala',
      'Garhshanker',
      'Ghagga',
      'Ghanaur',
      'Gidderbaha',
      'Gobindgarh',
      'Goniana',
      'Goraya',
      'Gurdaspur',
      'Guru Har Sahai',
      'Hajipur',
      'Handiaya',
      'Haryana',
      'Hoshiarpur',
      'Hussainpur',
      'Jagraon',
      'Jaitu',
      'Jalalabad',
      'Jalandhar',
      'Jalandhar Cantt.',
      'Jandiala',
      'Jugial',
      'Kalanaur',
      'Kapurthala',
      'Karoran',
      'Kartarpur',
      'Khamanon',
      'Khanauri',
      'Khanna',
      'Kharar',
      'Khem Karan',
      'Kot Fatta',
      'Kot Kapura',
      'Kurali',
      'Lehragaga',
      'Lodhian Khas',
      'Longowal',
      'Ludhiana',
      'Machhiwara',
      'Mahilpur',
      'Majitha',
      'Makhu',
      'Malerkotla',
      'Maloud',
      'Malout',
      'Mansa',
      'Maur',
      'Moga',
      'Moonak',
      'Morinda',
      'Mukerian',
      'Muktsar',
      'Mullanpur Dakha',
      'Mullanpur-Garibdas',
      'Nabha',
      'Nakodar',
      'Nangal',
      'Nawanshahr',
      'Nehon',
      'Noor Mahal',
      'Pathankot',
      'Patiala',
      'Patti',
      'Pattran',
      'Payal',
      'Phagwara',
      'Phillaur',
      'Qadian',
      'Rahon',
      'Raikot',
      'Rajasansi',
      'Rajpura',
      'Raman',
      'Ram Dass',
      'Rampura Phul',
      'Rayya',
      'Rupnagar',
      'Rurki Kasba',
      'S.A.S. Nagar (Mohali)',
      'Sahnewal',
      'Samana',
      'Samrala',
      'Sanaur',
      'Sangat',
      'Sangrur',
      'Sansarpur',
      'Sardulgarh',
      'Shahkot',
      'Shamchaurasi',
      'Shekhpura',
      'Sirhind-Fategarh',
      'Sri Hargobindpur',
      'Sujanpur',
      'Sultanpur Lodhi',
      'Sunam',
      'Talwandi Bhai',
      'Talwara',
      'Tappa',
      'Tarn Taran',
      'Urmar Tanda',
      'Zira',
      'Zirakpur'
    ],

    'Haryana': [
      'Ambala',
      'Ambala Cantt.',
      'Ambala Sadar',
      'Asan Khurd',
      'Assandh',
      'Ateli',
      'Babiyal',
      'Bahadurgarh',
      'Barwala',
      'Bawal',
      'Bawani Khera',
      'Beri',
      'Bhiwani',
      'Bilaspur',
      'Buria',
      'Charkhi Dadri',
      'Cheeka',
      'Chhachhrauli',
      'Dharuhera',
      'Dundahera',
      'Ellenabad',
      'Farakhpur',
      'Faridabad',
      'Farrukhnagar',
      'Fatehabad',
      'Ferozepur Jhirka',
      'Ganaur',
      'Gharaunda',
      'Gohana',
      'Gurgaon',
      'Gurgaon Rural',
      'Haileymandi',
      'Hansi',
      'Hassanpur',
      'Hathin',
      'Hisar',
      'Hodal',
      'Indri',
      'Jagadhri',
      'Jakhal Mandi',
      'Jhajjar',
      'Jind',
      'Julana',
      'Kaithal',
      'Kalan Wali',
      'Kalanaur',
      'Kalayat',
      'Kalka',
      'Kanina',
      'Kansepur',
      'Kardhan',
      'Karnal',
      'Kharkhoda',
      'Ladrawan',
      'Ladwa',
      'Loharu',
      'Maham',
      'Mahendragarh',
      'Mandi Dabwali',
      'Mustafabad',
      'Nagai Chaudhry',
      'Naraingarh',
      'Narnaul',
      'Narnaund',
      'Narwana',
      'Nilokheri',
      'Nuh',
      'Palwal',
      'Panchkula Urban Estate',
      'Panipat',
      'Panipat Taraf Ansar',
      'Panipat Taraf Rajputan',
      'Panipat Taraf Makhdum Zadgan',
      'Pataudi',
      'Pehowa',
      'Pinjore',
      'Punahana',
      'Pundri',
      'Radaur',
      'Raipur Rani',
      'Rania',
      'Ratia',
      'Rewari',
      'Rewari (Rural)',
      'Rohtak',
      'Sadaura',
      'Safidon',
      'Samalkha',
      'Sankhol',
      'Sasauli',
      'Shahbad',
      'Sirsa',
      'Siwani',
      'Sohna',
      'Sonipat',
      'Sukhrali',
      'Taoru',
      'Taraori',
      'Thanesar',
      'Tilpat',
      'Tohana',
      'Tosham',
      'Uchana',
      'Uklanamandi',
      'Uncha Siwana',
      'Yamunanagar'
    ],

    'Jammu & Kashmir': [
      'Achabal',
      'Akhnoor',
      'Anantnag',
      'Arnia',
      'Awantipora',
      'Badami Bagh',
      'Badgam',
      'Bandipore',
      'Banihal',
      'Baramula',
      'Bari Brahmana',
      'Bashohli',
      'Batote',
      'Beerwah',
      'Bhaderwah',
      'Bijbehara',
      'Billawar',
      'Bishna',
      'Charari Sharief',
      'Chenani',
      'Doda',
      'Duru-Verinag',
      'Ganderbal',
      'Gho Manhasan',
      'Gorah Salathian',
      'Gulmarg',
      'Hajan',
      'Handwara',
      'Hiranagar',
      'Jammu',
      'Jammu Cantonment',
      'Jourian',
      'Kargil',
      'Kathua',
      'Katra',
      'Khan Sahib',
      'Khour',
      'Khew',
      'Kishtwar',
      'Kud',
      'Kukernag',
      'Kulgam',
      'Kunzer',
      'Kupwara',
      'Lakhenpur',
      'Leh',
      'Magam',
      'Mattan',
      'Nowshehra',
      'Pahalgam',
      'Pampore',
      'Parole',
      'Pattan',
      'Pulwama',
      'Punch',
      'Qazigund',
      'Rajauri',
      'Ram Garh',
      'Ramban',
      'Ramnagar',
      'Ranbir Singh Pora',
      'Reasi',
      'Rehambal',
      'Samba',
      'Shupiyan',
      'Sopore',
      'Srinagar',
      'Sumbal',
      'Sunderbani',
      'Talwara',
      'Thanamandi',
      'Tral',
      'Udhampur',
      'Uri',
      'Vijay Pur'
    ],

    'Uttar Pradesh': [
      'Achhalda',
      'Achhnera',
      'Adari',
      'Afzalgarh',
      'Agarwal Mandi',
      'Agra',
      'Agra',
      'Ahraura',
      'Ailum',
      'Air Force Area',
      'Ajhuwa',
      'Akbarpur',
      'Akbarpur',
      'Aliganj',
      'Aligarh',
      'Allahabad',
      'Allahabad',
      'Allahganj',
      'Allapur',
      'Amanpur',
      'Ambehta',
      'Amethi',
      'Amethi',
      'Amila',
      'Amilo',
      'Aminagar Sarai',
      'Aminagar Urf Bhurbaral',
      'Amraudha',
      'Amroha',
      'Anandnagar',
      'Anpara',
      'Antu',
      'Anupshahr',
      'Aonla',
      'Armapur Estate',
      'Ashrafpur Kichhaauchha',
      'Atarra',
      'Atasu',
      'Atruali',
      'Atrauilia',
      'Auraiya',
      'Aurangabad',
      'Aurangabad Bangar',
      'Auras',
      'Awagarh',
      'Ayodhya',
      'Azamgarh',
      'Azizpur',
      'Azmatgarh',
      'Babarpur Ajitmal',
      'Baberu',
      'Babina',
      'Babrala',
      'Babugarh',
      'Bachhraon',
      'Bachhrawan',
      'Bad',
      'Baghpat',
      'Bah',
      'Bahadurganj',
      'Baheri',
      'Bahjoi',
      'Bahraich',
      'Bahsuma',
      'Bahuwa',
      'Bajna',
      'Bakewar',
      'Bakiabad',
      'Baldeo',
      'Ballia',
      'Balrampur',
      'Banat',
      'Banda',
      'Bangarmau',
      'Banki',
      'Bansdih',
      'Banggaon',
      'Bansi',
      'Baragaon',
      'Baragaon',
      'Baraut',
      'Bareilly',
      'Bareilly',
      'Barhalganj',
      'Barhani Bazar',
      'Barkhera',
      'Barsana',
      'Barua Sagar',
      'Barwar',
      'Basti',
      'Begumbad Budhana',
      'Behta Hajipur',
      'Bela Pratapgarh',
      'Belthara Road',
      'Beniganj',
      'Beswan',
      'Bewar',
      'Bhadarsa',
      'Bhadohi',
      'Bhagwant Nagar',
      'Bharatganj',
      'Bhargain',
      'Bharthana',
      'Bharuhana',
      'Bharwari',
      'Bhatni Bazar',
      'Bhatpar Rani',
      'Bhawan Bahadur Nagar',
      'Bhinga',
      'Bhogaon',
      'Bhojpur Dharampur',
      'Bhokarhedi',
      'Bhulepur',
      'Bidhuna',
      'Bighapur',
      'Bijnor',
      'Bijpur',
      'Bikapur',
      'Bilari',
      'Bilariaganj',
      'Bilaspur',
      'Bilaspur',
      'Bilgram',
      'Bilhaur',
      'Bilram',
      'Bilsanda',
      'Bilsi',
      'Bindki',
      'Bisalpur',
      'Bisanda Buzurg',
      'Bisauli',
      'Bisharatganj',
      'Bisokhar',
      'Biswan',
      'Bithoor',
      'Budan',
      'Budhana',
      'Bugrasi',
      'Bulandshahr',
      'Chail',
      'Chak Imam Ali',
      'Chakeri',
      'Chakia',
      'Chandauli',
      'Chandausi',
      'Chandpur',
      'Charkhari',
      'Charthaval',
      'Chaumuhan',
      'Chhaprauli',
      'Chharra Rafatpur',
      'Chhata',
      'Chhatari',
      'Chhibramau',
      'Chhutmalpur',
      'Chilkana Sultanpur',
      'Chirgaon',
      'Chitbara Gaon',
      'Chitrakoot Dham (Karwi)',
      'Chopan',
      'Choubepur Kalan',
      'Chunar',
      'Churk Ghurma',
      'Colonelganj',
      'Dadri',
      'Dalmau',
      'Dankaur',
      'Dariyabad',
      'Dasna',
      'Dataganj',
      'Daurala',
      'Dayalbagh',
      'Deoband',
      'Deoranian',
      'Deoria',
      'Dewa',
      'Dhampur',
      'Dhanauha',
      'Dhanauli',
      'Dhanaura',
      'Dharoti Khurd',
      'Dhaura Tanda',
      'Dhaurehra',
      'Dibai',
      'Dibiyapur',
      'Dildarnagar Fatehpur Bazar',
      'Doghat',
      'Dohrighat',
      'Dostpur',
      'Dudhi',
      'Dulhipur',
      'Ekdil',
      'Erich',
      'Etah',
      'Etawah',
      'Etmadpur',
      'Faizabad',
      'Faizabad',
      'Faizganj',
      'Farah',
      'Faridnagar',
      'Faridpur',
      'Faridpur',
      'Fariha',
      'Farrukhabad-Cum-Fatehgarh',
      'Fatehabad',
      'Fatehganj Pashchimi',
      'Fatehganj Purvi',
      'Fatehgarh',
      'Fatehpur',
      'Fatehpur',
      'Fatehpur Chaurasi',
      'Fatehpur Sikri',
      'Firozabad',
      'Gajraula',
      'Gangaghat',
      'Gangapur',
      'Gangoh',
      'Ganj Dundwara',
      'Ganj Muradabad',
      'Garautha',
      'Garhi Pukhta',
      'Garhmukteshwar',
      'Gaura Barhaj',
      'Gauri Bazar',
      'Gausganj',
      'Gawan',
      'Ghatampur',
      'Ghaziabad',
      'Ghazipur',
      'Ghiraur',
      'Ghorawal',
      'Ghosi',
      'Ghosia Bazar',
      'Ghughuli',
      'Gohand',
      'Gokul',
      'Gola Bazar',
      'Gola Gokarannath',
      'Gonda',
      'Gopamau',
      'Gopiganj',
      'Gorakhpur',
      'Gosainganj',
      'Gosainganj',
      'Govardhan',
      'Gulaothi',
      'Gularia Bhindara',
      'Gulariya',
      'Gunnaur',
      'Gursahiganj',
      'Gursarai',
      'Gyanpur',
      'Hafizpur',
      'Haidergarh',
      'Haldaur',
      'Hamirpur',
      'Handia',
      'Hapur',
      'Hardoi',
      'Harduaganj',
      'Hargaon',
      'Hariharpur',
      'Harraiya',
      'Hasanpur',
      'Hasayan',
      'Hastinapur',
      'Hata',
      'Hathras',
      'Hyderabad',
      'Ibrahim Pur',
      'Iglas',
      'Ikauna',
      'Iltifatganj Bazar',
      'Indian Telephone Industry, Mankapur (Sp. Village)',
      'Islamnagar',
      'Itaunja',
      'Jafarabad',
      'Jagner',
      'Jahanabad',
      'Jahangirabad',
      'Jahangirpur',
      'Jais',
      'Jaithara',
      'Jalalabad',
      'Jalalabad',
      'Jalalabad',
      'Jalali',
      'Jalalpur',
      'Jalaun',
      'Jalesar',
      'Jamshila',
      'Jangipur',
      'Jansath',
      'Jarwal',
      'Jasrana',
      'Jaswantnagar',
      'Jatari',
      'Jaunpur',
      'Jewar',
      'Jhalu',
      'Jhansi',
      'Jhansi',
      'Jhansi Rly. Settlement',
      'Jhijhak',
      'Jhijhana',
      'Jhusi',
      'Jhusi Kohna',
      'Jiyanpur',
      'Joya',
      'Jyoti Khuria',
      'Kabra',
      'Kachhauna Patseni',
      'Kachhla',
      'Kachhwa',
      'Kadaura',
      'Kadipur',
      'Kailashpur',
      'Kaimganj',
      'Kairana',
      'Kakgaina',
      'Kakod',
      'Kakori',
      'Kakrala',
      'Kalinagar',
      'Kalpi',
      'Kamalganj',
      'Kampil',
      'Kandhla',
      'Kandwa',
      'Kannauj',
      'Kanpur',
      'Kanpur',
      'Kanth',
      'Kanth',
      'Kaptanganj',
      'Karari',
      'Karhal',
      'Karnawal',
      'Kasganj',
      'Katariya',
      'Katghar Lalganj',
      'Kathera',
      'Katra',
      'Katra',
      'Katra Medniganj',
      'Kauriagan',
      'Kemri',
      'Kerakat',
      'Khadda',
      'Khaga',
      'Khailar',
      'Khair',
      'Khairabad',
      'Khairabad',
      'Khalilabad',
      'Khamaria',
      'Khanpur',
      'Khairela',
      'Khargupur',
      'Khariya',
      'Kharkhoda',
      'Khatauli',
      'Khatauli Rural',
      'Khekada',
      'Kheragarh',
      'Kheri',
      'Kheta Sarai',
      'Khudaganj',
      'Khurja',
      'Khutar',
      'Kiraoli',
      'Kiratpur',
      'Kishni',
      'Kishunpur',
      'Kithaur',
      'Koeripur',
      'Konch',
      'Kopaganj',
      'Kora Jahanabad',
      'Koraon',
      'Korwa',
      'Kosi Kalan',
      'Kota',
      'Kotra',
      'Kotwa',
      'Kul Pura',
      'Kundarki',
      'Kurara',
      'Kursath',
      'Kursi',
      'Kurthia',
      'Kusumba',
      'Kushinagar',
      'Lakhna',
      'Lal Gopalganj Nindaura',
      'Lalganj',
      'Lalitpur',
      'Lar',
      'Lawar NP',
      'Ledwa Mahua',
      'Lohta',
      'Loni',
      'Lucknow',
      'Lucknow',
      'Machhlishahr',
      'Madhoganj',
      'Madhogarh',
      'Maghar',
      'Mahaban',
      'Mahmudabad',
      'Mahoba',
      'Maholi',
      'Mahona',
      'Maharajganj',
      'Maharajganj',
      'Maharajganj',
      'Mahroni',
      'Mailani',
      'Mainpuri',
      'Majhara Pipar Ehatmali',
      'Majhauli Raj',
      'Malihabad',
      'Mallawan',
      'Mandawar',
      'Manikpur',
      'Manikpur Sarhat',
      'Maniyar',
      'Manjhanpur',
      'Mankapur',
      'Marehra',
      'Mariahu',
      'Maruadih Rly. Settlement',
      'Maswasi',
      'Mataundh',
      'Mathura',
      'Mathura',
      'Mau Aima',
      'Maudaha',
      'Maunath Bhanjan',
      'Mauranipur',
      'Maurawan',
      'Mawana',
      'Meerut',
      'Meerut',
      'Mehdawal',
      'Mehnagar',
      'Mendu',
      'Milak',
      'Miranpur',
      'Mirganj',
      'Mirzapur-Cum-Vindhyachal',
      'Miskrik-Cum-Neemsar',
      'Modinagar',
      'Mogra Badshahpur',
      'Mohammadabad',
      'Mohammadabad',
      'Mohammadi',
      'Mohan',
      'Mohanpur',
      'Mohiyuddinpur',
      'Moradabad',
      'Moth',
      'Mubarakpur',
      'Mughal Sarai',
      'Mughal Sarai Rly. Settlement',
      'Muhammadabad',
      'Mukrampur Khema',
      'Mundera Bazar',
      'Mundia',
      'Muradnagar',
      'Mursan',
      'Musafirkhana',
      'Muzaffarnagar',
      'Nadigaon',
      'Nagina',
      'Nagram',
      'Nai Bazar',
      'Nainana Jat',
      'Najibabad',
      'Nakur',
      'Nanauta',
      'Nandgaon',
      'Nanpara',
      'Naraini',
      'Narauli',
      'Naraura',
      'Naugawan Sadat',
      'Nautanwa',
      'Nawabganj',
      'Nawabganj',
      'Nawabganj',
      'Nawabganj',
      'Nehtaur',
      'Nichlaul',
      'Nidhauli Kalan',
      'Niwari',
      'Nizamabad',
      'Noida',
      'Noorpur',
      'Northern Rly. Colony',
      'Nyoria Husainpur',
      'Nyotini',
      'Obra',
      'Oel Dhakwa',
      'Orai',
      'Oran',
      'Ordnance Factory Muradnagar',
      'Pachperwa',
      'Padrauna',
      'Pahasu',
      'Paintepur',
      'Pali',
      'Pali',
      'Palia Kalan',
      'Parasi',
      'Parichha',
      'Parikshitgarh',
      'Parsadepur',
      'Patala',
      'Patiyali',
      'Patti',
      'Phalauda',
      'Phaphund',
      'Phulpur',
      'Phulpur',
      'Phulwaria',
      'Pihani',
      'Pilibhit',
      'Pilkhana',
      'Pilkhwa',
      'Pinahat',
      'Pipalsana Chaudhari',
      'Pipiganj',
      'Pipraich',
      'Pipri',
      'Powayan',
      'Pratapgarh City',
      'Pukhryan',
      'Puranpur',
      'Purdilnagar',
      'Purquazi',
      'Purwa',
      'Qasimpur Power House Colony',
      'Rabupura',
      'Radhakund',
      'Rae Bareli',
      'Raja Ka Rampur',
      'Rajapur',
      'Ramkola',
      'Ramnagar',
      'Ramnagar',
      'Rampur',
      'Rampur Bhawanipur',
      'Rampur Karkhana',
      'Rampur Maniharan',
      'Rampura',
      'Ranipur',
      'Rashidpur Garhi',
      'Rasra',
      'Rasulabad',
      'Rath',
      'Raya',
      'Renukoot',
      'Reoti',
      'Richha',
      'Risia Bazar',
      'Rithora',
      'Rly. Settlement Roza',
      'Robertsganj',
      'Rudauli',
      'Rudayan',
      'Rudrapur',
      'Rura',
      'Rustamnagar Sahaspur',
      'Sadabad',
      'Sadat',
      'Safipur',
      'Saharanpur',
      'Sahaspur',
      'Sahaswan',
      'Sahatwar',
      'Sahawar',
      'Sahjanwa',
      'Sahpau NP',
      'Saidpur',
      'Saidpur',
      'Sainthal',
      'Saiyad Raja',
      'Sakhanu',
      'Sakit',
      'Salarpur Khadar',
      'Salempur',
      'Salon',
      'Sambhal',
      'Samdhan',
      'Samthar',
      'Sandi',
      'Sandila',
      'Sarai Aquil',
      'Sarai Mir',
      'Sardhana',
      'Sarila',
      'Sarsawan',
      'Sasni',
      'Satrikh',
      'Saunkh',
      'Saurikh',
      'Seohara',
      'Sewalkhas',
      'Sewarhi',
      'Shahabad',
      'Shahabad',
      'Shahganj',
      'Shahi',
      'Shahjahanpur',
      'Shahjahanpur',
      'Shahpur',
      'Shamli',
      'Shamsabad',
      'Shamsabad',
      'Shankargarh',
      'Shergarh',
      'Sherkot',
      'Shikarpur',
      'Shikohabad',
      'Shishgarh',
      'Shivdaspur',
      'Shivli',
      'Shivrajpur',
      'Shohratgarh',
      'Siana',
      'Siddhaur',
      'Sidhauli',
      'Sidhpura',
      'Sikanderpur',
      'Sikanderpur',
      'Sikandra',
      'Sikandra Rao',
      'Sikandrabad',
      'Singahi Bhiraura',
      'Sirathu',
      'Sirauli',
      'Sirsa',
      'Sirsagan',
      'Sirsi',
      'Sisauli',
      'Siswa Bazar',
      'Sitapur',
      'Som',
      'Soron',
      'Suar',
      'Sukhmalpur Nizamabad',
      'Sultanpur',
      'Sumerpur',
      'Suriyawan',
      'Swamibagh',
      'Talbehat',
      'Talgram',
      'Tambaur-Cum-Ahmadabad',
      'Tanda',
      'Tanda',
      'Tatapur Lallu',
      'Tetri Bazar',
      'Thakurdwara',
      'Thana Bhawan',
      'Thiriya Nizamat Khan',
      'Tikait Nagar',
      'Tikri',
      'Tilhar',
      'Tindwari',
      'Tirwaganj',
      'Titron',
      'Tondi Fatehpur',
      'Tulsipur',
      'Tundla',
      'Tundla Kham',
      'Tundla Rly. Colony',
      'Ugu',
      'Ujhani',
      'Ujhari',
      'Umri',
      'Umri Kalan',
      'Un',
      'Unchahar',
      'Unnao',
      'Usawan',
      'Usehat',
      'Utraula',
      'Varanasi',
      'Varanasi',
      'Vijaigarh',
      'Vrindavan',
      'Warhampur',
      'Wazirganj',
      'Zaidpur',
      'Zamania'
    ],

    'New Delhi': [
      'Alipur',
      'Asola',
      'Babar Pur',
      'Bankner',
      'Bawana',
      'Begum Pur',
      'Bhalswa Jahangir Pur',
      'Bhati',
      'Burari',
      'Chhawla',
      'Chilla Saroda Bangar',
      'Dallo Pura',
      'Dayal Pur',
      'Delhi Cantt.',
      'Delhi Municipal Corporation (U)',
      'Deoli',
      'Gharoli',
      'Gharonda Neemka Bangar Alias Patpar Ganj',
      'Gheora',
      'Ghitorni',
      'Ghoga',
      'Gokal Pur',
      'Hastsal',
      'Jaffrabad',
      'Jharoda Majra Burari',
      'Jiwal Pur Alias Johri Pur',
      'Jona Pur',
      'Kanjhawala',
      'Kapas Hera',
      'Karawal Nagar',
      'Khajoori Khas',
      'Khera Khurd',
      'Kirari Suleman Nagar',
      'Kondli',
      'Libas Pur',
      'Mirpur Turk',
      'Mithe Pur',
      'Molar Band',
      'Mundka',
      'Mustafabad',
      'Nangal Dewat',
      'Nangal Thakran',
      'Nangloi Jat',
      'New Delhi Municipal Council',
      'Pehlad Pur Bangar',
      'Pooth Kalan',
      'Pooth Khurd',
      'Pul Pehlad',
      'Quamruddin Nagar',
      'Rajokri',
      'Roshan Pura Alias Dichaon Khurd',
      'Sadat Pur Gujran',
      'Sahibabad Daulat Pur',
      'Saidul Ajaib',
      'Sambhalka',
      'Sanoth',
      'Siras Pur',
      'Sultan Pur',
      'Sultan Pur Majra',
      'Taj Pul',
      'Tigri',
      'Ziauddin Pur'
    ],

    "Rajasthan": [
      '1 SGM',
      '3 STR',
      'Abu Road',
      'Ajmer',
      'Aklera',
      'Alwar',
      'Amet',
      'Antah',
      'Anupgarh',
      'Asind',
      'Baggar',
      'Bagru',
      'Bakani',
      'Bali',
      'Balotra',
      'Bandikui',
      'Banswara',
      'Baran',
      'Bari',
      'Bari Sadri',
      'Barmer',
      'Basni Belima',
      'Bayana',
      'Beawar',
      'Beejoliya Kalan',
      'Begun',
      'Behat',
      'Behror',
      'Bhadra',
      'Bhalariya',
      'Bharatpur',
      'Bhawani Mandi',
      'Bhilwara',
      'Bhinder',
      'Bhinmal',
      'Bhiwadi',
      'Bhusawar',
      'Bidasar',
      'Bikaner',
      'Bilara',
      'Bissau',
      'Budhpura',
      'Bundi',
      'Chaksu',
      'Chechat',
      'Chhabra',
      'Chhapar',
      'Chipabarod',
      'Chhoti Sadri',
      'Chirawa',
      'Chittaurgarh',
      'Chomu',
      'Churu',
      'Dariba',
      'Dausa',
      'Deeg',
      'Deoli',
      'Deshnoke',
      'Devgarh',
      'Dhariawad',
      'Dhaulpur',
      'Didwana',
      'Dungargarh',
      'Dungarpur',
      'Fatehnagar',
      'Fatehpur',
      'Gajsinghpur',
      'Galiakot',
      'Ganganagar',
      'Gangapur',
      'Gangapur City',
      'Goredi Chancha',
      'Gothra',
      'Govindgarh',
      'Gulabpura',
      'Hanumangarh',
      'Hindaun',
      'Indragarh',
      'Jahazpur',
      'Jaipur',
      'Jaisalmer',
      'Jaitaran',
      'Jalor',
      'Jhalawar',
      'Jhalrapatan',
      'JhunJhunun',
      'Jobner',
      'Jodhpur',
      'Kaithoon',
      'Kaman',
      'Kanor',
      'Kapasan',
      'Kaprain',
      'Karanpur',
      'Karauli',
      'Kekri',
      'Keshoraipatan',
      'Kesrisinghpur',
      'Khairthal',
      'Khandel',
      'Kherli',
      'Kherliganj',
      'Kherwara Chhaoni',
      'Khetri',
      'Kiranipura',
      'Kishangarh',
      'Kishangarh Renwal',
      'Kolvi Mandi Rajendra Pura',
      'Kota',
      'Kotputli',
      'Kuchaman City',
      'Kuchera',
      'Kumbhkot',
      'Kumher',
      'Kushalgarh',
      'Lachhmangarh',
      'Ladnu',
      'Lakheri',
      'Lalsot',
      'Losal',
      'Mahu Kalan',
      'Mahwa',
      'Makrana',
      'Malpura',
      'Mandalgarh',
      'Mandawa',
      'Mandawar',
      'Mangrol',
      'Manohar Thana',
      'Marwar Junction',
      'Merta City',
      'Modak',
      'Mount Abu',
      'Mukandgarh',
      'Mundwa',
      'Nadbai',
      'Nagar',
      'Nagaur',
      'Nainwa',
      'Nasirabad',
      'Nathdwara',
      'Nawa',
      'Nawalgadh',
      'Neem-Ka-Thana',
      'Newa Talai',
      'Nimbahera',
      'Niwai',
      'Nohar',
      'Nokha',
      'Padampur',
      'Pali',
      'Parbatsar',
      'Partapur',
      'Phalna',
      'Phalodi',
      'Phulera',
      'Pilani',
      'Pilibanga',
      'Pindwara',
      'Piparcity',
      'Pirawa',
      'Pokaran',
      'Pratapgarh',
      'Pushkar',
      'Raisinghnagar',
      'Rajakhera',
      'Rajaldesar',
      'Rajgarh',
      'Rajsamand',
      'Ramganj Mandi',
      'Ramgarh',
      'Rani',
      'Ratangarh',
      'Ratannagar',
      'Rawatbhata',
      'Rawatsar',
      'Reengus',
      'Rikhabdeo',
      'Sadri',
      'Sadulshahar',
      'Sagwara',
      'Salumbar',
      'Sambhar',
      'Sanchore',
      'Sangaria',
      'Sangod',
      'Sardarsahar',
      'Sarwar',
      'Satalkheri',
      'Sawai Madhopur',
      'Shahpura',
      'Sheoganj',
      'Sikar',
      'Sirohi',
      'Sogariya',
      'Sojat',
      'Sojat Road',
      'Sri Madhopur',
      'Sujangarh',
      'Suket',
      'Sumerpur',
      'Surajgarh',
      'Suratgarh',
      'Takhathgarh',
      'Taranagar',
      'Tijara',
      'Todabhim',
      'Todaraisingh',
      'Todra',
      'Tonk',
      'Udaipur',
      'Udaipurwati',
      'Udpura',
      'Uniara',
      'Vanasthali',
      'Vidyavihar',
      'Vijainagar',
      'Viratnagar',
      'Weir'
    ],

    "Himachal Pradesh": [
      'Arki',
      'Baddi',
      'Bakloh',
      'Banjar',
      'Bhpota',
      'Bhuntar',
      'Bilaspur',
      'Chamba',
      'Chaupal',
      'Chuari Khas',
      'Dagshai',
      'Dalhousie',
      'Dalhousie',
      'Daulatpur',
      'Dera Gopipur',
      'Dharmsala',
      'Gagret',
      'Ghumarwin',
      'Hamirpur',
      'Jawalamukhi',
      'Jogindarnagar',
      'Jubbal',
      'Jutogh',
      'Kangra',
      'Kasauli',
      'Kotkhai',
      'Kullu',
      'Manali',
      'Mandi',
      'Mant Khas',
      'Mehatpur Basdehra',
      'Nadaun',
      'Nagrota Bagwan',
      'Nahan',
      'Naina Devi',
      'Nalagadh',
      'Narkanda',
      'Nurpur',
      'Palampur',
      'Paonta Sahib',
      'Parwanoo',
      'Rajgarh',
      'Rampur',
      'Rawalsar',
      'Rohr',
      'Sabathu',
      'Santokhgarh',
      'Sarkaghat',
      'Seoni',
      'Shimla',
      'Solan',
      'Sundarnagar',
      'Talai',
      'Theog',
      'Tira Sujanpur',
      'Una',
      'Yol'
    ],

    "Uttarakhand": [
      'Almora',
      'Badrinathpuri',
      'Bageshwar',
      'Bajpur',
      'Banbasa',
      'Bandia',
      'Barkot',
      'Bharat Heavy Electrical Limited Ranipur',
      'Bhimal',
      'Bhowali',
      'Chakrata',
      'Chamba',
      'Chamoli Gopeshwar',
      'Champawat',
      'Clement Town',
      'Dehradun',
      'Dehradun',
      'Dev Prayag',
      'Dhaluwala',
      'Dhandera',
      'Dharchula',
      'Dharchula Dehat',
      'Didihat',
      'Dineshpur',
      'Dogadda',
      'Doiwala',
      'Dwarahat',
      'FRI And College Area',
      'Gadarpur',
      'Gangotri',
      'Gochar',
      'Haldwani-Cum-Kathgodam',
      'Hardwar',
      'Herbertpur',
      'Jaspur',
      'Jhabrera',
      'Joshimath',
      'Kachnal Gosain',
      'Kaladungi',
      'Karn Prayag',
      'Kashipur',
      'Kashirampur',
      'Kedarnath',
      'Kela Khera',
      'Khatima',
      'Kichha',
      'Kirtinagar',
      'Kotdwar',
      'Laksar',
      'Lalkuan',
      'Landaura',
      'Landour',
      'Lansdowne',
      'Lohaghat',
      'Mahua Dabra Haripura',
      'Mahua Kheraganj',
      'Manglaur',
      'Mohanpur Mohammadpur',
      'Muni Ki Reti',
      'Mussoori',
      'Nagla',
      'Nainital',
      'Nainital',
      'Nand Prayag',
      'Narendra Nagar',
      'Pauri',
      'Pithoragarh',
      'Pratitnagar',
      'Raipur',
      'Ramnagar',
      'Ranikhet',
      'Rishikesh',
      'Roorkee',
      'Roorkee',
      'Rudra Prayag',
      'Rudrapur',
      'Shaktigarh',
      'Sitarganj',
      'Srinagar',
      'Sultanpur',
      'Tanakpur',
      'Tehri',
      'Uttarkashi',
      'Veerbhadra',
      'Vikasnagar'
    ],

    // South Zone
    'Karnataka': [
      'Adityapatna',
      'Adyar',
      'Afzalpur',
      'Aland',
      'Alnavar',
      'Alur',
      'Ambikanagara',
      'Anekal',
      'Ankola',
      'Annigeri',
      'Arkalgud',
      'Arsikere',
      'Athni',
      'Aurad',
      'Badami',
      'Bagalkot',
      'Bagepalli',
      'Bail Hongal',
      'Bajala',
      'Bajpe',
      'Bangalore',
      'Bangarapet',
      'Bankapura',
      'Bannur',
      'Bantwal',
      'Basavakalyan',
      'Basavana Bagewadi',
      'Belgaum',
      'Belgaum Cantonment',
      'Bellary',
      'Beltangadi',
      'Belur',
      'Belvata',
      'Bhadravati',
      'Bhalki',
      'Bhatkal',
      'Bhimarayanagudi',
      'Bhogadi',
      'Bidar',
      'Bijapur',
      'Bilgi',
      'Birur',
      'Bommanahalli',
      'Bommasandra',
      'Byadgi',
      'Byatarayanapura',
      'Challakere',
      'Chamrajnagar',
      'Channagiri',
      'Channapatna',
      'Channarayapatna',
      'Chik Ballapur',
      'Chikmagalur',
      'Chiknayakanhalli',
      'Chikodi',
      'Chincholi',
      'Chintamani',
      'Chitapur',
      'Chitgoppa',
      'Chitradurga',
      'Dandeli',
      'Dargajogihalli',
      'Dasarahalli',
      'Davanagere',
      'Devadurga',
      'Devanhalli',
      'Dod Ballapur',
      'Donimalai Township',
      'Gadag-Betigeri',
      'Gajendragarh',
      'Gangawati',
      'Gauribidanur',
      'Gokak',
      'Gokak Falls',
      'Gonikoppal',
      'Gottikere',
      'Gubbi',
      'Gudibanda',
      'Gulbarga',
      'Guledgudda',
      'Gundlupet',
      'Gurmatkal',
      'Haliyal',
      'Hangal',
      'Harihar',
      'Harapanahalli',
      'Hassan',
      'Hatti',
      'Hatti Gold Mines',
      'Haveri',
      'Hebbagodi',
      'Hebbalu',
      'Heggadadevankote',
      'Herohalli',
      'Hindalgi',
      'Hirekerur',
      'Hiriyur',
      'Holalkere',
      'Holenarsipur',
      'Homnabad',
      'Honnavar',
      'Honnali',
      'Hoovina Hadagalli',
      'Hosanagara',
      'Hosdurga',
      'Hoskote',
      'Hospet',
      'Hubli-Dharwad',
      'Hukeri',
      'Hunasamaranahalli',
      'Hungund',
      'Hunsur',
      'Ilkal',
      'Indi',
      'Jagalur',
      'Jamkhandi',
      'Jevargi',
      'Jog Falls',
      'Kadur',
      'Kalghatgi',
      'Kamalapuram',
      'Kampli',
      'Kanakapura',
      'Kangrali (BK)',
      'Kangrali (KH)',
      'Kannur',
      'Karkal',
      'Karwar',
      'Kengeri',
      'Kerur',
      'Khanapur',
      'Kodigenahalli',
      'Kodiyal',
      'Kolar',
      'Kollegal',
      'Konanakunte',
      'Konnur',
      'Koppa',
      'Koppal',
      'Koratagere',
      'Kotekara',
      'Kothnur',
      'Kotturu',
      'Krishnarajanagar',
      'Krishnarajapura',
      'Krishnarajasagara',
      'Krishnarajpet',
      'Kudchi',
      'Kudligi',
      'Kudremukh',
      'Kumta',
      'Kundapura',
      'Kundgol',
      'Kunigal',
      'Kurgunta',
      'Kushalnagar',
      'Kushtagi',
      'Lakshmeshwar',
      'Lingsugur',
      'Londa',
      'Maddur',
      'Madhugiri',
      'Madikeri',
      'Magadi',
      'Mahadevapura',
      'Mahalingpur',
      'Malavalli',
      'Mallad',
      'Malur',
      'Mandya',
      'Mangalore',
      'Manvi',
      'Molakalmuru',
      'Mudalgi',
      'Mudbidri',
      'Muddebhihal',
      'Mudgal',
      'Mudhol',
      'Mudigere',
      'Mudushedde',
      'Mulbagal',
      'Mulgund',
      'Mulki',
      'Mulur',
      'Mundargi',
      'Mundgod',
      'Munirabad Project Area',
      'Munnur',
      'Mysore',
      'Nagamangala',
      'Nanjangud',
      'Narasimharajapura',
      'Naregal',
      'Nargund',
      'Navalgund',
      'Nelamangala',
      'Nipani',
      'Pandavapura',
      'Pattangere',
      'Pavagada',
      'Piryapatna',
      'Pudu',
      'Puttur',
      'Rabkavi Banhatti',
      'Raichur',
      'Ramanagaram',
      'Ramdurg',
      'Ranibennur',
      'Raybag',
      'Robertson Pet',
      'Ron',
      'Sadalgi',
      'Sagar',
      'Sakleshpur',
      'Saligram',
      'Sandur',
      'Sankeshwar',
      'Sathyamangala',
      'Saundatti-Yellamma',
      'Savanur',
      'Sedam',
      'Shahabad',
      'Shahabad ACC',
      'Shahpur',
      'Shaktinagar',
      'Shiggaon',
      'Shikarpur',
      'Shimoga',
      'Shirhatti',
      'Shorapur',
      'Shrirangapattana',
      'Siddapur',
      'Sidlaghatta',
      'Sindgi',
      'Sindhnur',
      'Sira',
      'Siralkoppa',
      'Sirsi',
      'Siruguppa',
      'Someshwar',
      'Somvarpet',
      'Sorab',
      'Sringeri',
      'Srinivasapur',
      'Sulya',
      'Talikota',
      'Tarikere',
      'Tekkalkota',
      'Terdal',
      'Thokur-62',
      'Thumbe',
      'Tiptur',
      'Tirthahalli',
      'Tirumakudal-Narsipur',
      'Tumkur',
      'Turuvekere',
      'Udupi',
      'Ullal',
      'Uttarahalli',
      'Venkatapura',
      'Vijayapura',
      'Virajpet',
      'Wadi',
      'Wadi ACC',
      'Yadgir',
      'Yelahanka',
      'Yelandur',
      'Yelbarga',
      'Yellapur',
      'Yenagudde'
    ],

    'Tamil Nadu': [
      'Thirumuruganpoondi',
      'Vellalapatti',
      'Abiramam',
      'Achampudur',
      'Acharapakkam',
      'Acharipallam',
      'Achipatti',
      'Adikaratti',
      'Adiramapattinam',
      'Aduthurai Alias Maruthuvakudi',
      'Agaram',
      'Agastheeswaram',
      'Alagappapuram',
      'Alampalayam',
      'Alandur',
      'Alanganallur',
      'Alangayam',
      'Alangudi',
      'Alangulam',
      'Alangulam',
      'Alanthurai',
      'Alapakkam',
      'Allapuram',
      'Alur',
      'Alwarkurichi',
      'Alwarthirunagiri',
      'Ambasamudram',
      'Ambattur',
      'Ambur',
      'Ammainaickanur',
      'Ammapettai',
      'Ammapettai',
      'Ammavarikuppam',
      'Ammoor',
      'Anaimalai',
      'Anaiyur',
      'Anaiyur',
      'Anakaputhur',
      'Ananthapuram',
      'Andipalayam',
      'Andipatti Jakkampatti',
      'Anjugramam',
      'Annamalai Nagar',
      'Annavasal',
      'Annur',
      'Anthiyur',
      'Appakudal',
      'Arachalur',
      'Arakandanallur',
      'Arakonam',
      'Aralvaimozhi',
      'Arani',
      'Arani',
      'Aranthangi',
      'Arasiramani',
      'Aravakurichi',
      'Aravankad',
      'Arcot',
      'Arimalam',
      'Ariyalur',
      'Ariyappampalayam',
      'Ariyur',
      'Arumanai',
      'Arumbavur',
      'Arumuganeri',
      'Aruppukkottai',
      'Ashokapuram',
      'Athani',
      'Athanur',
      'Athimarapatti',
      'Athipattu',
      'Athur',
      'Athur',
      'Attayampatti',
      'Attur',
      'Avadattur',
      'Avadi',
      'Avalpoondurai',
      'Avanashi',
      'Avaniapuram',
      'Ayakudi',
      'Aygudi',
      'Ayothiapattinam',
      'Ayyalur',
      'Ayyampalayam',
      'Ayyampettai',
      'Ayyampettai',
      'Azhagiapandiapuram',
      'B. Mallapuram',
      'B. Meenakshipuram',
      'Balakrishnampatti',
      'Balakrishnapuram',
      'Balapallam',
      'Balasamudram',
      'Bargur',
      'Batlagundu',
      'Belur',
      'Bhavani',
      'Bhavanisagar',
      'Bhuvanagiri',
      'Bikketti',
      'Bodinayakkanur',
      'Boothapandi',
      'Boothipuram',
      'Brahmana Periya-Agraharam',
      'Chengalpattu',
      'Chengam',
      'Chennai',
      'Chennasamudram',
      'Chennimalai',
      'Cheranmadevi',
      'Chetpet',
      'Chettiarpatti',
      'Chettipalayam',
      'Chettipalayam',
      'Chettithangal',
      'Chidambaram',
      'Chinna Anuppanadi',
      'Chinnakkampalayam',
      'Chinnalapatti',
      'Chinnamanur',
      'Chinnampalayam',
      'Chinnasalem',
      'Chinnasekkadu',
      'Chinnavedampatti',
      'Chithode',
      'Chitlapakkam',
      'Cholapuram',
      'Coimbatore',
      'Coonoor',
      'Courtalam',
      'Cuddalore',
      'Dalavaipatti',
      'Denkanikottai',
      'Desur',
      'Devadanapatti',
      'Devakottai',
      'Devanangurichi',
      'Devarshola',
      'Dhalavoipuram',
      'Dhali',
      'Dhaliyur',
      'Dharapadavedu',
      'Dharapuram',
      'Dharasuram',
      'Dharmapuri',
      'Dindigul',
      'Dusi',
      'Edaganasalai',
      'Edaikodu',
      'Edakalinadu',
      'Edappadi',
      'Elathur',
      'Elayirampannai',
      'Elumalai',
      'Eral',
      'Eraniel',
      'Eriodu',
      'Erode',
      'Erumaipatti',
      'Eruvadi',
      'Ethapur',
      'Ettayapuram',
      'Ettimadai',
      'Ezhudesam',
      'Ganapathipuram',
      'Gandhi Nagar(Katpadi Ext.)',
      'Gangaikondan',
      'Gangavalli',
      'Ganguvarpatti',
      'Gingee',
      'Gobichettipalayam',
      'Gopalasamudram',
      'Goundampalayam',
      'Gudalur',
      'Gudalur',
      'Gudalur',
      'Gudiyatham',
      'Gummidipoondi',
      'Hanumanthampatti',
      'Harur',
      'Harveypatti',
      'Highways',
      'Hosur',
      'Hubbathala',
      'Huligal',
      'Idikarai',
      'Ilampillai',
      'Ilanji',
      'Iluppaiyurani',
      'Iluppur',
      'Inam Karur',
      'Injambakkam',
      'Irugur',
      'Jaffrabadi',
      'Jagathala',
      'Jalakandapuram',
      'Jalladiampet',
      'Jambai',
      'Jayankondam',
      'Jolarpet',
      'Kadambur',
      'Kadathur',
      'Kadayal',
      'Kadayampatti',
      'Kadayanallur',
      'Kalakkad',
      'Kalambur',
      'Kalapatti',
      'Kalappanaickenpatti',
      'Kalavai',
      'Kalinjur',
      'Kaliakkavilai',
      'Kalladaikurichi',
      'Kallakkurichi',
      'Kallakudi',
      'Kallukuttam',
      'Kalugumalai',
      'Kamayagoundanpatti',
      'Kambainallur',
      'Kambam',
      'Kamuthi',
      'Kanadukathan',
      'Kanakkampalayam',
      'Kanam',
      'Kancheepuram',
      'Kandanur',
      'Kangayampalayam',
      'Kangeyam',
      'Kangeyanallur',
      'Kaniyur',
      'Kanjikoil',
      'Kannadendal',
      'Kannamangalam',
      'Kannampalayam',
      'Kannankurichi',
      'Kannivadi',
      'Kannivadi',
      'Kanniakumari',
      'Kappiyarai',
      'Karaikkudi',
      'Karamadai',
      'Karamakkam',
      'Karamakkudi',
      'Kariamangalam',
      'Kariapatti',
      'Karugampattur',
      'Karumandi Chellipalayam',
      'Karumathampatti',
      'Karungal',
      'Karunguzhi',
      'Karuppur',
      'Karur',
      'Kasipalayam (E)',
      'Kasipalayam (G)',
      'Kathujuganapalli',
      'Katpadi',
      'Kattivakkam',
      'Kattumannarkoil',
      'Kattuputhur',
      'Kaveripakkam',
      'Kaveripattinam',
      'Kayalpattinam',
      'Kayatharu',
      'Keelakarai',
      'Keeramangalam',
      'Keeranur',
      'Keeranur',
      'Keeripatti',
      'Keezhapavur',
      'Kelamangalam',
      'Kembainaickenpalayam',
      'Kethi',
      'Kilampadi',
      'Kilkulam',
      'Kilkunda',
      'Killyur',
      'Killlai',
      'Kilpennathur',
      'Kilvelur',
      'Kinathukaduvu',
      'Kodaiakanal',
      'Kodavasal',
      'Kodumudi',
      'Kolachal',
      'Kolappalur',
      'Kolathupalayam',
      'Kolathur',
      'Kollankodu',
      'Kollankoil',
      'Komaralingam',
      'Kombai',
      'Konavattam',
      'Kondalampatti',
      'Konganapuram',
      'Koorai Kundu',
      'Koothappar',
      'Koradacheri',
      'Kotagiri',
      'Kothinallur',
      'Kottaiyur',
      'Kottakuppam',
      'Kottaram',
      'Kottivakkam',
      'Kottur',
      'Kouthanallur',
      'Kovilpatti',
      'Krishnagiri',
      'Krishnarayapuram',
      'Krishnasamudram',
      'Kuchanur',
      'Kuhalur',
      'Kulasekarapuram',
      'Kulithalai',
      'Kumarapalayam',
      'Kumarapuram',
      'Kumbakonam',
      'Kundrathur',
      'Kuniyamuthur',
      'Kunnathur',
      'Kurichi',
      'Kurinjipadi',
      'Kurudampalayam',
      'Kurumbalur',
      'Kuthalam',
      'Kuzhithurai',
      'Labbaikudikadu',
      'Lakkampatti',
      'Lalgudi',
      'Lalpet',
      'Llayangudi',
      'Madambakkam',
      'Madathukulam',
      'Madavaram',
      'Madippakkam',
      'Madukkarai',
      'Madukkur',
      'Madurai',
      'Maduranthakam',
      'Maduravoyal',
      'Mallamooppampatti',
      'Mallankinaru',
      'Mallasamudram',
      'Mallur',
      'Mamallapuram',
      'Mamsapuram',
      'Manachanallur',
      'Manali',
      'Manalmedu',
      'Manalurpet',
      'Manamadurai',
      'Manapakkam',
      'Manapparai',
      'Manavalakurichi',
      'Mandai Kadu',
      'Mandapam',
      'Mangadu',
      'Mangal',
      'Mangalampet',
      'Manimutharu',
      'Mannargudi',
      'Mappilaiurani',
      'Maraimalainagar',
      'Marakkanam',
      'Maramangala Thupatti',
      'Marandahalli',
      'Markayankottai',
      'Marudur',
      'Marungur',
      'Mathigiri',
      'Mayiladuthurai',
      'Mecheri',
      'Meenambakkam',
      'Melacheval',
      'Melachokkanathapuram',
      'Melagaram',
      'Melamaiyur',
      'Melamadai',
      'Melathiruppanthuruthi',
      'Melattur',
      'Melpattampakkam',
      'Melur',
      'Melvisharam',
      'Mettupalayam',
      'Mettur',
      'Minjur',
      'Modakurichi',
      'Mohanur',
      'Moolakaraipatti',
      'Moovarasampettai',
      'Mopperipalayam',
      'Mudukulathur',
      'Mukasipidariyur',
      'Mukkudal',
      'Mulagumudu',
      'Mulanur',
      'Muruganpalayam',
      'Musiri',
      'Muthupet',
      'Muthur',
      'Muttayyapuram',
      'Myladi',
      'Naduvattam',
      'Nagapattinam',
      'Nagavakulam',
      'Nagercoil',
      'Nagojanahalli',
      'Nallampatti',
      'Nallur',
      'Namagiripettai',
      'Namakkal',
      'Nambiyur',
      'Nandambakkam',
      'Nandivaram-Guduvancheri',
      'Nangavalli',
      'Nangavaram',
      'Nanguneri',
      'Nanjikottai',
      'Nannilam',
      'Naranammalpuram',
      'Naranapuram',
      'Narasimhanaickenpalayam',
      'Narasangapuram',
      'Naravarikuppam',
      'Nasiyanur',
      'Natham',
      'Nathampannai',
      'Natrampalli',
      'Nattapettai',
      'Nattarasan Kottai',
      'Navalpattu',
      'Nazerath',
      'Needamangalam',
      'Neelagiri',
      'Neelankarai',
      'Neikkarappatti',
      'Neiyyur',
      'Nellikuppam',
      'Nelliyalam',
      'Nemili',
      'Neripperichal',
      'Nerkunram',
      'Nerkuppai',
      'Nerunjipettai',
      'Neykkarappatti',
      'Neyveli',
      'Nilakkottai',
      'Odaipatti',
      'Odaayakulam',
      'Oddanchatram',
      'Odugathur',
      'Oggiyamduraipakkam',
      'Olagadam',
      'Omalur',
      'Orathanadu (Mukthambalpuram)',
      'Othakadai',
      'Othakalmandapam',
      'Ottapparai',
      'P.J. Cholapuram',
      'P.Mettupalayam',
      'P.N.Patti',
      'Pacode',
      'Padaiveedu',
      'Padianallur',
      'Padirikuppam',
      'Padmanabhapuram',
      'Palaganangudy',
      'Palakkodu',
      'Palamedu',
      'Palani',
      'Palani Chettipatti',
      'Palavakkam',
      'Palavansathu',
      'Palayam',
      'Palladam',
      'Pallapalaiyam',
      'Pallapatti',
      'Pallathur',
      'Pallavaram',
      'Pallikaranai',
      'Pallikonda',
      'Pallipalayam',
      'Pallipalayam Agraharam',
      'Pallipattu',
      'Pammal',
      'Panagudi',
      'Panaimarathupatti',
      'Panapakkam',
      'Panboli',
      'Pandamangalam',
      'Pannaikadu',
      'Pannaipuram',
      'Panruti',
      'Papanasam',
      'Pappankurichi',
      'Papparapatti',
      'Papireddipatti',
      'Paramakudi',
      'Paramathi',
      'Parangipettai',
      'Paravai',
      'Pasur',
      'Pathamadai',
      'Pattinam',
      'Pattiveeranpatti',
      'Pattukottai',
      'Pazhugal',
      'Peerkankaranai',
      'Pennadam',
      'Pennagaram',
      'Pennathur',
      'Peraiyur',
      'Peralam',
      'Perambalur',
      'Peranamallur',
      'Peravurani',
      'Periya Negamam',
      'Periyakodiveri',
      'Periyakulam',
      'Periyanaickenpalayam',
      'Periyapatti',
      'Periyasemur',
      'Pernampattu',
      'Perumagalur',
      'Perumandi',
      'Perumuchi',
      'Perundurai',
      'Perungalathur',
      'Perungudi',
      'Perungulam',
      'Perur',
      'Pethampalayam',
      'Pethanaickenpalayam',
      'Pillanallur',
      'Polichalur',
      'Pollachi',
      'Polur',
      'Ponmani',
      'Ponnamaravathi',
      'Ponnampatti',
      'Ponneri',
      'Poolambadi',
      'Poolampatti',
      'Pooluvapatti',
      'Poonamallee',
      'Porur',
      'Pothanur',
      'Pothatturpettai',
      'Pudukadai',
      'Pudukottai',
      'Pudupalayam',
      'Pudupatti',
      'Pudupattinam',
      'Pudur (S)',
      'Puduvayal',
      'Puliyankudi',
      'Puliyur',
      'Pullampadi',
      'Punjai Thottakurichi',
      'Punjaipugalur',
      'Punjaipuliampatti',
      'Puthalam',
      'Puvalur',
      'Puzhal',
      'Puzhithivakkam (Ullagaram)',
      'R.Pudupatti',
      'R.S.Mangalam',
      'Rajapalayam',
      'Ramanathapuram',
      'Ramapuram',
      'Rameswaram',
      'Ranipettai',
      'Rasipuram',
      'Rayagiri',
      'Reethapuram',
      'Rosalpatti',
      'Rudravathi',
      'S.Kannanur',
      'S.Kodikulam',
      'S.Nallur',
      'Salangapalayam',
      'Salem',
      'Samalapuram',
      'Samathur',
      'Sambavar Vadagarai',
      'Sankaramanaallur',
      'Sankarankoil',
      'Sankarapuram',
      'Sankari',
      'Sankarnagar',
      'Saravanampatti',
      'Sarcarsamakulam',
      'Sathankulam',
      'Sathiyavijayanagaram',
      'Sathuvachari',
      'Sathyamangalam',
      'Sattur',
      'Sayalgudi',
      'Sayapuram',
      'Seerapalli',
      'Seeveur',
      'Seithur',
      'Sembakkam',
      'Semmipalayam',
      'Senthamangalam',
      'Sentharapatti',
      'Senur',
      'Sethaiathoppu',
      'Sevilimedu',
      'Sevugampatti',
      'Shenbakkam',
      'Shenkottai',
      'Sholavandan',
      'Sholingannallur',
      'Sholinger',
      'Sholur',
      'Sikkarayapuram',
      'Singampuneri',
      'Singaperumalkoil',
      'Sirkali',
      'Sirugamani',
      'Sirumugai',
      'Sithayankottai',
      'Sithurajapuram',
      'Sivaganga',
      'Sivagiri',
      'Sivakasi',
      'Sivanthipuram',
      'Srimushnam',
      'Sriperumbudur',
      'Sriramapuram',
      'Srivaikuntam',
      'Srivilliputhur',
      'St. Thomas Mount-Cum-Pallavaram',
      'Suchindram',
      'Suleeswaranpatti',
      'Sulur',
      'Sundarapandiam',
      'Sundarapandiapuram',
      'Surampatti',
      'Surandai',
      'Suriyampalayam',
      'Swamimalai',
      'T.Kallupatti',
      'Tambaram',
      'Tayilupatti',
      'Tenkasi',
      'Thadikombu',
      'Thakkolam',
      'Thalainayar',
      'Thalakudi',
      'Thamarikulam',
      'Thammampatti',
      'Thanjavur',
      'Thanthoni',
      'Tharamangalam',
      'Tharangambadi',
      'Thathaiyangarpettai',
      'Thedavur',
      'Thenambakkam',
      'Thengampudur',
      'Theni Allinagaram',
      'Thenkarai',
      'Thenthamaraikulam',
      'Thenthiruperai',
      'Thesur',
      'Thevaram',
      'Thevur',
      'Thiagadurgam',
      'Thingalnagar',
      'Thiruk Karungudi',
      'Thirukattupalli',
      'Thirumalaiyampalayam',
      'Thirumangalam',
      'Thirumazhisai',
      'Thirunagar',
      'Thirunageswaram',
      'Thiruneermalai',
      'Thirunindravur',
      'Thiruparankundram',
      'Thiruparappu',
      'Thiruporur',
      'Thiruppanandal',
      'Thiruppuvanam',
      'Thiruthangal',
      'Thiruthuraipoondi',
      'Thiruvaiyaru',
      'Thiruvalam',
      'Thiruvallur',
      'Thiruvarur',
      'Thiruvattaru',
      'Thiruvengatam',
      'ThiruvennaiNallur',
      'Thiruverumbur',
      'Thiruvidaimarudur',
      'Thiruvithankodu',
      'Thisayanvilai',
      'Thittacheri',
      'Thondamuthur',
      'Thondi',
      'Thoothukkudi',
      'Thorapadi',
      'Thottipalayam',
      'Thottiyam',
      'Thudiyalur',
      'Thuraiyur',
      'Thuthipattu',
      'Thuvakudi',
      'Timiri',
      'Tindivanam',
      'Tiruchendur',
      'Tiruchengode',
      'Tiruchirappalli',
      'Tirukalukundram',
      'Tirukkoyilur',
      'Tirunelveli',
      'Tirupathur',
      'Tiruppur',
      'Tirusulam',
      'Tiruttani',
      'Tiruvannamalai',
      'Tiruverkadu',
      'Tiruvethipuram',
      'Tiruvotiyur',
      'Tittakudi',
      'TNPL Pugalur',
      'Udangudi',
      'Udayarpalayam',
      'Udhagamandalam',
      'Udumalpet',
      'Ullur',
      'Ulundurpet',
      'Unjalaur',
      'Unnamalaikadai',
      'Uppidamangalam',
      'Uppiliapuram',
      'Urapakkam',
      'Usilampatti',
      'Uthamapalayam',
      'Uthangarai',
      'Uthayendram',
      'Uthiramerur',
      'Uthukottai',
      'Uthukuli',
      'V. Pudur',
      'Vadakarai Keezhpadugai',
      'Vadakkanandal',
      'Vadakkuvalliyur',
      'Vadalur',
      'Vadamadurai',
      'Vadavalli',
      'Vadipatti',
      'Vadugapatti',
      'Vaitheeswarankoil',
      'Valangaiman',
      'Valasaravakkam',
      'Valavanur',
      'Vallam',
      'Valparai',
      'Valvaithankoshtam',
      'Vanavasi',
      'Vandalur',
      'Vandavasi',
      'Vandiyur',
      'Vaniputhur',
      'Vaniyambadi',
      'Varadarajanpettai',
      'Vasudevanallur',
      'Vathirairuppu',
      'Vazhapadi',
      'Vedapatti',
      'Vedaranyam',
      'Vedasandur',
      'Veeraganur',
      'Veerakeralam',
      'Veerakkalpudur',
      'Veerapandi',
      'Veerapandi',
      'Veerapandi',
      'Veerappanchatram',
      'Veeravanallur',
      'Velampalayam',
      'Velankanni',
      'Vellakinai',
      'Vellakoil',
      'Vellalur',
      'Vellimalai',
      'Vellore',
      'Vellottamparappu',
      'Velur',
      'Vengampudur',
      'Vengathur',
      'Venkrai',
      'Vennanthur',
      'Veppathur',
      'Verkilambi',
      'Vettaikaranpudur',
      'Vettavalam',
      'Vijayapuri',
      'Vikramasingapuram',
      'Vikravandi',
      'Vilangudi',
      'Vilankurichi',
      'Vilapakkam',
      'Vilathikulam',
      'Vilavur',
      'Villukuri',
      'Viluppuram',
      'Virudhachalam',
      'Virudhunagar',
      'Virupakshipuram',
      'Viswanatham',
      'Walajabad',
      'Walajapet',
      'Wellington',
      'Zamin Uthukuli'
    ],

    'Kerala': [
      'Adoor',
      'Akathiyoor',
      'Alappuzha',
      'Aluva',
      'Ancharakandy',
      'Angamaly',
      'Arookutty',
      'Aroor',
      'Attingal',
      'Avinissery',
      'Azhikode North',
      'Azhikode South',
      'Bangramanjeshwar',
      'Beypore',
      'Brahmakulam',
      'Chala',
      'Chalakudy',
      'Changanassery',
      'Chavakkad',
      'Chelora',
      'Chendamangalam',
      'Chengamanad',
      'Chengannur',
      'Cheranallur',
      'Cherthala',
      'Cheruthazham',
      'Cheruvannur',
      'Chevvoor',
      'Chirakkal',
      'Chittur-Thathamangalam',
      'Chockli',
      'Choornikkara',
      'Chowwara',
      'Dharmadom',
      'Edathala',
      'Elayavoor',
      'Eloor',
      'Eranholi',
      'Erattupetta',
      'Feroke',
      'Guruvayoor',
      'Hosabettu',
      'Idukki Township',
      'Iringaprom',
      'Irinjalakuda',
      'Iriveri',
      'Kadachira',
      'Kadamakkudy',
      'Kadirur',
      'Kadungalloor',
      'Kalamassery',
      'Kallisseri',
      'Kalpetta',
      'Kanhangad',
      'Kanhirode',
      'Kanjikkuzhi',
      'Kannadiparamba',
      'Kannapuram',
      'Kannur',
      'Kannur Cantonment',
      'Karuvanthuruthy',
      'Kasaragod',
      'Kayamkulam',
      'Kochi',
      'Kodungallur',
      'Kokkothamangalam',
      'Kolazhy',
      'Kollam',
      'Komalapuram',
      'Koothuparamba',
      'Koratty',
      'Kothamangalam',
      'Kottayam',
      'Kottayam-Malabar',
      'Kottuvally',
      'Kozhikode',
      'Kudlu',
      'Kunnamkulam',
      'Kureeekad',
      'Malappuram',
      'Manjeri',
      'Manjeshwar',
      'Maradu',
      'Marathakkara',
      'Mattannur',
      'Mavelikkara',
      'Mavilayi',
      'Mavoor',
      'Methala',
      'Muhamma',
      'Mulavukad',
      'Munderi',
      'Muvattupuzha',
      'Muzhappilangad',
      'Nadathara',
      'Narath',
      'Nedumangad',
      'Nenmenikkara',
      'New Mahe',
      'Neyyattinkara',
      'Olavanna',
      'Ottappalam',
      'Paduvilaiyi',
      'Palai',
      'Palakkad',
      'Palayad',
      'Palissery',
      'Pallikkunnu',
      'Paluvai',
      'Panniyannur',
      'Panoor',
      'Pantheeramkavu',
      'Pappinisseri',
      'Paravoor',
      'Paravur',
      'Pathanamthitta',
      'Pathiriyad',
      'Pattiom',
      'Pavaratty',
      'Payyannur',
      'Perakam',
      'Peralasseri',
      'Peringathur',
      'Perinthalmanna',
      'Perumbaikad',
      'Perumbavoor',
      'Pinarayi',
      'Ponnani',
      'Pottore',
      'Punalur',
      'Puranattukara',
      'Puthukkad',
      'Puthunagaram',
      'Puzhathi',
      'Quilandy',
      'Ramanattukara',
      'Shoranur',
      'Taliparamba',
      'Thaikkad',
      'Thalassery',
      'Thiruvalla',
      'Thiruvankulam',
      'Thodupuzha',
      'Thottada',
      'Thrippunithura',
      'Thrissur',
      'Tirur',
      'Trivandrum',
      'Udma',
      'Vadakara',
      'Vaikom',
      'Valapattanam',
      'Vallachira',
      'Varam',
      'Varappuzha',
      'Varkala',
      'Vazhakkala',
      'Venmanad',
      'Villiappally'
    ],

    'Andhra Pradesh': [
      'Adilabad',
      'Adoni',
      'Akkampalle',
      'Akkayapalle',
      'Alwal',
      'Amadalavalasa',
      'Amalapuram',
      'Anakapalle',
      'Anantapur',
      'Asifabad',
      'Badepalle',
      'Bandarulanka',
      'Bapatla',
      'Bellampalle',
      'Bestavaripeta',
      'Bethamcheria',
      'Bhadrachalam',
      'Bhainsa',
      'Bheemavaram',
      'Bheemunipatnam',
      'Bhongir',
      'Bobbili',
      'Bodhan',
      'Bollaram',
      'Bugganipalle',
      'Chandur',
      'Chatakonda',
      'Chemmumiahpet',
      'Chilakaluripet',
      'Chinnachowk',
      'Chintalavalasa',
      'Chirala',
      'Chittoor',
      'Choutuppal',
      'Chunchupalle',
      'Cuddapah',
      'Dasnapur',
      'Devarakonda',
      'Dharmavaram',
      'Dommara Nandyal',
      'Dowleswaram',
      'Eddumailaram',
      'Ekambara Kuppam',
      'Eluru',
      'Farooqnagar',
      'Gaddi Annaram',
      'Gadwal',
      'Gajapathinagaram',
      'Gajularega',
      'Gajuwaka',
      'Ghatkesar',
      'Gooty',
      'Gudivada',
      'Gudivada',
      'Gudur',
      'Guntakal',
      'Guntur',
      'Hindupur',
      'Hyderabad M.Corp',
      'Ichchapuram',
      'Isnapur',
      'Jaggayyapet',
      'Jagtial',
      'Jallaram Kamanpur',
      'Jammalamadugu',
      'Jangaon',
      'Jarjapupeta',
      'Kadiri',
      'Kaghaznagar',
      'Kakinada',
      'Kallur',
      'Kalyandurg',
      'Kamareddy',
      'Kanapaka',
      'Kandukur',
      'Kantabamsuguda',
      'Kanuru',
      'Kapra',
      'Karimnagar',
      'Kavali',
      'Khammam',
      'Koratla',
      'Kothagudem',
      'Kothavalasa',
      'Kovurpalle',
      'Kovvur',
      'Kukatpalle',
      'Kuppam',
      'Kurnool',
      'Kyathampalle',
      'L.B. Nagar',
      'Macherla',
      'Machilipatnam',
      'Madanapalle',
      'Madaram',
      'Mahbubnagar',
      'Malkajgiri',
      'Mancherial',
      'Mandamarri',
      'Mandapeta',
      'Mangalagiri',
      'Manugur',
      'Markapur',
      'Medak',
      'Meerpet',
      'Miryalguda',
      'Moragudi',
      'Nagari',
      'Nagarkurnool',
      'Nalgonda',
      'Nandyal',
      'Narasarapet',
      'Narayanavanam',
      'Narayanpet',
      'Narsapur',
      'Narsingi',
      'Narsipatnam',
      'Naspur',
      'Nellimaria',
      'Nellore',
      'Nidadavole',
      'Nirmal',
      'Nizamabad',
      'Nuzvid',
      'Omerkhan Daira',
      'Ongole',
      'Osmania University',
      'Palacole',
      'Palakurthi',
      'Palasa @ Kasibugga',
      'Palwancha',
      'Pamur',
      'Papampeta',
      'Parvathipuram',
      'Patancheru',
      'Pedana',
      'Peddapuram',
      'Pitapuram',
      'Ponnur',
      'Proddatur',
      'Punganur',
      'Puttur',
      'Quthbullapur',
      'Rajahmundry',
      'Rajam',
      'Rajendranagar',
      'Ramachandrapuram',
      'Ramachandrapuram',
      'Ramachandrapuram-BHEL Township',
      'Ramagundam',
      'Ramanayyapeta',
      'Ramapuram',
      'Rameswaram',
      'Rampachodavaram',
      'Rayachoti',
      'Rayadurg',
      'Renigunta',
      'Repalle',
      'Sadasivpet',
      'Salur',
      'Samalkota',
      'Sangareddy',
      'Sarapaka',
      'Sattenapalle',
      'Secunderabad',
      'Serilingampalle',
      'Siddipet',
      'Singapur',
      'Singarayakonda',
      'Sirsilla',
      'Sompeta',
      'Srikakulam',
      'Srikalahasti',
      'Sriramnagar',
      'Srisailam Project (RFC) Township',
      'Srisailamgudem Devasthanam',
      'Suryapet',
      'Suryaraopeta',
      'Tadepalligudem',
      'Tadpatri',
      'Tallapalle',
      'Tandur',
      'Tanuku',
      'Teegalapahad',
      'Tenali',
      'Tiruchanur',
      'Tirumala',
      'Tirupati',
      'Tirupati (NMA)',
      'Tuni',
      'Uppal Kalan',
      'Upper Sileru Project Site Camp',
      'Uravakonda',
      'Vaparala',
      'Venkatagiri',
      'Vepagunta',
      'Vetapalem',
      'Vicarabad',
      'Vijayapuri (North)',
      'Vijayawada',
      'Vinukonda',
      'Visakhapatnam',
      'Vizianagaram',
      'Wanaparthi',
      'Warangal',
      'Yadagirigutta',
      'Yellandu',
      'Yemmiganur',
      'Yerraguntla',
      'Zahirabad'
    ],

    'Telangana': [
      'Hyderabad',
      'Secunderabad',
      'Khammam',
      'Karimnagar',
      'Miryalaguda',
      'Warangal',
      'Siddipet',
      'Nalgonda',
      'Kazipet',
      'Nizamabad',
      'Hayathnagar',
      'Mahbubnagar',
      'L B Nagar Hyderabad',
      'Mancherial',
      'Kothagudem',
      'Thirumalgiri',
      'Suryapet'
    ],

    'Lakshadweep': ['Amini', 'Kavaratti', 'Minicoy'],

    'Pondicherry': [
      'Karaikal',
      'Kurumbapet',
      'Mahe',
      'Ozhukarai',
      'Pondicherry',
      'Yanam'
    ],

    // Central Zone
    'Madhya Pradesh': [
      'Agar',
      'Ajaigarh',
      'Akoda',
      'Akodia',
      'Alampur',
      'Alirajpur',
      'Alot',
      'Amanganj',
      'Amarkantak',
      'Amarpatan',
      'Amarwara',
      'Ambada',
      'Ambah',
      'Amla',
      'Amlai',
      'Anjad',
      'Antari',
      'Anuppur',
      'Aron',
      'Ashok Nagar',
      'Ashta',
      'Babai',
      'Bada Malhera',
      'Badagaon',
      'Badagoan',
      'Badarwas',
      'Badawada',
      'Badi',
      'Badkuhi',
      'Badnagar',
      'Badnawar',
      'Badod',
      'Badoda',
      'Badra',
      'Bagh',
      'Bagli',
      'Baihar',
      'Baikunthpur',
      'Balaghat',
      'Baldeogarh',
      'Bamhani',
      'Bamor',
      'Bamora',
      'Banda',
      'Bangawan',
      'Bansatar Kheda',
      'Baraily',
      'Barela',
      'Barghat',
      'Barhi',
      'Barigarh',
      'Barwaha',
      'Barwani',
      'Basoda',
      'Begamganj',
      'Beohari',
      'Berasia',
      'Betma',
      'Betul',
      'Betul-Bazar',
      'Bhainsdehi',
      'Bhamodi',
      'Bhander',
      'Bhanpura',
      'Bharveli',
      'Bhaurasa',
      'Bhavra',
      'Bhedaghat',
      'Bhikangaon',
      'Bhilakhedi',
      'Bhind',
      'Bhitwar',
      'Bhopal',
      'Biaora',
      'Bijawar',
      'Bijeypur',
      'Bijuri',
      'Bilaura',
      'Bilpura',
      'Bina Etawa',
      'Bina Rly Colony',
      'Birsinghpur',
      'Boda',
      'Budhni',
      'Burhanpur',
      'Burhar',
      'Buxwaha',
      'Chachaura-Binaganj',
      'Chakghat',
      'Chandameta-Butaria',
      'Chanderi',
      'Chandia',
      'Chandla',
      'Chaurai Khas',
      'Chhatarpur',
      'Chhindwara',
      'Chhota Chhindwara (Gottegaon)',
      'Chichli',
      'Chitrakoot',
      'Churhat',
      'Daboh',
      'Dabra',
      'Damoh',
      'Damua',
      'Datia',
      'Deodara',
      'Deori',
      'Depalpur',
      'Devendranagar',
      'Devhara',
      'Dewas',
      'Dhamnod',
      'Dhana',
      'Dhanpuri',
      'Dhar',
      'Dharampuri',
      'Dighawani',
      'Diken',
      'Dindori',
      'Dola',
      'Dongar Parasia',
      'Dumar Kachhar',
      'G.C.F Jabalpur',
      'Gadarwara',
      'Gairatganj',
      'Garhakota',
      'Garhi-Malhara',
      'Garoth',
      'Ghansor',
      'Ghuwara',
      'Gogapur',
      'Gohad',
      'Gormi',
      'Govindgarh',
      'Guna',
      'Gurh',
      'Gwalior',
      'Hanumana',
      'Harda',
      'Harpalpur',
      'Harrai',
      'Harsud',
      'Hatod',
      'Hatpiplya',
      'Hatta',
      'Hindoria',
      'Hirapur',
      'Hoshangabad',
      'Ichhawar',
      'Iklehra',
      'Indergarh',
      'Indore',
      'Isagarh',
      'Itarsi',
      'Jabalpur',
      'Jabalpur Cantt.',
      'Jaisinghnagar',
      'Jaithari',
      'Jaitwara',
      'Jamai',
      'Jaora',
      'Jata Chhapar',
      'Jatara',
      'Jawad',
      'Jawar',
      'Jeron Khalasa',
      'Jhabua',
      'Jhundpura',
      'Jiran',
      'Jirapur',
      'Jobat',
      'Joura',
      'Kailaras',
      'Kakarhati',
      'Kali Chhapar',
      'Kanad',
      'Kannod',
      'Kantaphod',
      'Kareli',
      'Karera',
      'Kari',
      'Karnawad',
      'Karrapur',
      'Kasrawad',
      'Katangi',
      'Kelhauri(Chachai)',
      'Khachrod',
      'Khajuraho',
      'Khand(Bansagar)',
      'Khandwa',
      'Khaniyadhana',
      'Khargapur',
      'Khargone',
      'Khategaon',
      'Khetia',
      'Khilchipur',
      'Khirkiya',
      'Khujner',
      'Khurai',
      'Kolaras',
      'Kotar',
      'Kothi',
      'Kotma',
      'Kukshi',
      'Kumbhraj',
      'Kurwai',
      'Kymore',
      'Lahar',
      'Lakhnadon',
      'Lateri',
      'Laundi',
      'Lidhorakhas',
      'Lodhikheda',
      'Loharda',
      'Machalpur',
      'Maharajpur',
      'Maheshwar',
      'Mahidpur',
      'Maihar',
      'Majholi',
      'Makronia',
      'Maksi',
      'Malaj Khand',
      'Malhargarh',
      'Manasa',
      'Manawar',
      'Mandav',
      'Mandideep',
      'Mandla',
      'Mandlekshwar',
      'Mandsaur',
      'Manegaon',
      'Mangawan',
      'Manglaya Sadak',
      'Manpur',
      'Mau',
      'Mauganj',
      'Meghnagar',
      'Mehara Gaon',
      'Mehgaon',
      'Mhow Cantt.',
      'Mhowgaon',
      'Mihona',
      'Mohgaon',
      'Morar Cantt.',
      'Morena',
      'Multai',
      'Mundi',
      'Mungaoli',
      'Murwara (Katni)',
      'Nagda',
      'Nagod',
      'Nagri',
      'Nai Garhi',
      'Nainpur',
      'Nalkheda',
      'Namli',
      'Narayangarh',
      'Narsimhapur',
      'Narsinghgarh',
      'Narwar',
      'Nasrullagan',
      'Naudhia',
      'Neemuch',
      'Nepanagar',
      'Neuton Chikhli Kalan',
      'Niwar',
      'Nowgaon',
      'Nowrozabad(Khodargama)',
      'O.F.Khamaria',
      'Obedullaganj',
      'Omkarehwar',
      'Orchha',
      'Ordinance Factory Itarsi',
      'Pachmarhi Cantt',
      'Pachore',
      'Pal Chourai',
      'Palda',
      'Palera',
      'Pali',
      'Panagar',
      'Panara',
      'Pandhana',
      'Pandhurna',
      'Panna',
      'Pansemal',
      'Pasan',
      'Patan',
      'Patharia',
      'Pawai',
      'Petlawad',
      'Phuphkalan',
      'Pichhore',
      'Pipariya',
      'Piploada',
      'Piplya Mandi',
      'Pithampur',
      'Polay Kalan',
      'Porsa',
      'Prithvipur',
      'Raghogarh-Vijaypur',
      'Rahatgarh',
      'Raisen',
      'Rajakhedi',
      'Rajgarh',
      'Rajgarh',
      'Rajnagar',
      'Rajpur',
      'Rampur Baghelan',
      'Rampur Naikin',
      'Rampura',
      'Ranapur',
      'Ratangarh',
      'Ratlam',
      'Ratlam Rly. Colony (Ratlam Kasba)',
      'Rau',
      'Rehli',
      'Rehti',
      'Rewa',
      'Runji Gautampura',
      'Sabalgarh',
      'Sagar',
      'Sagar Cantt.',
      'Sailana',
      'Sanawad',
      'Sanchi',
      'Sarangpur',
      'Sardarpur',
      'Sarni',
      'Satai',
      'Satna',
      'Satwas',
      'Sausar',
      'Sawer',
      'Sehore',
      'Semaria',
      'Sendhwa',
      'Seondha',
      'Seoni',
      'Seoni Malwa',
      'Sethia',
      'Shahdol',
      'Shahgarh',
      'Shahpur',
      'Shahpura',
      'Shajapur',
      'Shamgarh',
      'Sheopur',
      'Shivpuri',
      'Shujalpur',
      'Sidhi',
      'Sihora',
      'Singoli',
      'Singrauli',
      'Sinhasa',
      'Sirgora',
      'Sirmaur',
      'Sironj',
      'Sitamau',
      'Sohagpur',
      'Sonkatch',
      'Soyatkalan',
      'Suhagi',
      'Sultanpur',
      'Susner',
      'Suthaliya',
      'Tal',
      'Talen',
      'Tarana',
      'Taricharkalan',
      'Tekanpur',
      'Tendu Kheda',
      'Teonthar',
      'Thandla',
      'Tikamgarh',
      'Timarni',
      'Tirodi',
      'Udaipura',
      'Ujjain',
      'Ukwa',
      'Umaria',
      'Unchehara',
      'Unhel',
      'Vehicle Fac. Jabalpur',
      'Vidisha',
      'Vijayraghavgadh',
      'Wara Seoni'
    ],

    'Chhattisgarh': [
      'Ahiwara',
      'Akaltara',
      'Ambagarh Chowki',
      'Ambikapur',
      'Arang',
      'Bade Bacheli',
      'Bagbahara',
      'Baikunthpur',
      'Balod',
      'Baloda',
      'Baloda Bazar',
      'Banarsi',
      'Basna',
      'Bemetra',
      'Bhanpuri',
      'Bhatapara',
      'Bhatgaon',
      'Bhilai Charoda',
      'Bhilai Nagar',
      'Bilaspur',
      'Bilha',
      'Birgaon',
      'Bodri',
      'Champa',
      'Chharchha',
      'Chhuiikhandan',
      'Chirmiri',
      'Dalli-Rajhara',
      'Dantewada',
      'Deori',
      'Dhamdha',
      'Dhamtari',
      'Dharamjaigarh',
      'Dipka',
      'Dongargaon',
      'Dongragarh',
      'Durg',
      'Frezarpur',
      'Gandai',
      'Gaurella',
      'Geedam',
      'Gharghoda',
      'Gobranawapara',
      'Gogaon',
      'Hatkachora',
      'Jagdalpur',
      'Jamul',
      'Jashpur Nagar',
      'Jhagrakhand',
      'Kanker',
      'Katghora',
      'Kawardha',
      'Khairagarh',
      'Khamhria',
      'Kharod',
      'Kharsia',
      'Khongapani',
      'Kirandul',
      'Kondagaon',
      'Korba',
      'Kota',
      'Kumhari',
      'Kurud',
      'Lingiyaidih',
      'Lormi',
      'Mahasamund',
      'Manendragarh',
      'Mehmand',
      'Mowa',
      'Mungeli',
      'Naila Janjgir',
      'Namna Kalan',
      'Naya Baradwar',
      'Pandariya',
      'Patan',
      'Pathalgaon',
      'Pendriya',
      'Phunderdiari',
      'Pithora',
      'Raigarh',
      'Raipur',
      'Rajgamaar',
      'Rajnandgaon',
      'Ramanujganj',
      'Ratanpur',
      'Sakti',
      'Saraipali',
      'Sarangarh',
      'Shivrinayan',
      'Simga',
      'Sirgiti',
      'Surajpur',
      'Takhatpur',
      'Telgaon',
      'Tilda Newra',
      'Urla',
      'Vishrampur'
    ],

    // North East Zone
    'Assam': [
      'Abhayapuri',
      'Ambikapur Part-X',
      'Amguri',
      'Anand Nagar',
      'Badarpur',
      'Badarpur Rly Town',
      'Bahbari Gaon',
      'Bamun Sualkuchi',
      'Barbari (AMC Area)',
      'Barpathar',
      'Barpeta',
      'Barpeta Road',
      'Basugaon',
      'Bihpuria',
      'Bijni',
      'Bilasipara',
      'Biswanath Chariali',
      'Bohari',
      'Bokajan',
      'Bokakhat',
      'Bongaigaon',
      'Bongaigaon, Refinery & Petro-Chemical Ltd. Township',
      'Borgolai Grant No.11',
      'Chabua',
      'Chandrapur Bagicha',
      'Chapar',
      'Chekonidhara',
      'Choto Haibor',
      'Dergao',
      'Dharapur',
      'Dhekiajuli',
      'Dhemaji',
      'Dhing',
      'Dhubri',
      'Dibrugarh',
      'Digboi',
      'Digboi Oil Town',
      'Dimaruguri',
      'Diphu',
      'Doboka',
      'Dokmoka',
      'Donkamokam',
      'Doom Dooma',
      'Duliajan No.1',
      'Duliajan Oil Town',
      'Durga Nagar Part-V',
      'Gauripur',
      'Goalpara',
      'Gohpur',
      'Golaghat',
      'Golokganj',
      'Gossaigaon',
      'Guwahati',
      'Haflong',
      'Hailakandi',
      'Hamren',
      'Hindustan Paper Corporation Ltd. Township Area Panchgram',
      'Hojai',
      'Howli',
      'Howraghat',
      'Jagiroad',
      'Jonai Bazar',
      'Jorhat',
      'Kampur Town',
      'Kanakpur Part-II',
      'Karimganj',
      'Kharijapikon',
      'Kharupatia',
      'Kochpara',
      'Kokrajhar',
      'Kumar Kaibarta Gaon',
      'Lakhipur',
      'Lakhipur',
      'Lala',
      'Lanka',
      'Lido Tikok',
      'Lido Town',
      'Lumdung',
      'Lumdung Rly Colony',
      'Mahur',
      'Maibong',
      'Majgaon',
      'Makum',
      'Mangaldoi',
      'Mankachar',
      'Margherita',
      'Mariani',
      'Marigaon',
      'Moran Town',
      'Moranhat',
      'Nagaon',
      'Naharkatiya',
      'Nalbari',
      'Namrup',
      'Naubaisa Gaon',
      'Nazira',
      'New Bongaigaon Rly. Colony',
      'North Guwahati',
      'North Lakhimpur',
      'Numaligarh Refinery Township',
      'Palasbari',
      'Pathsala',
      'Rangapara',
      'Rangia',
      'Salakati',
      'Sapatgram',
      'Sarbhog',
      'Sarthebar',
      'Sarupathar',
      'Sarupathar Bengali',
      'Senchoa Gaon',
      'Sibsagar',
      'Silapathar',
      'Silchar',
      'Silchar Part-X',
      'Sonari',
      'Sualkuchi',
      'Tangla',
      'Tezpur',
      'Tihu',
      'Tinsukia',
      'Titabor Town',
      'Udalguri',
      'Umrangso',
      'Uttar Krishnapur Part-I'
    ],

    'Arunachal Pradesh': [
      'Along',
      'Basar',
      'Bomdila',
      'Changlang',
      'Daporijo',
      'Deomali',
      'Itanagar',
      'Jairampur',
      'Khonsa',
      'Naharlagun',
      'Namsai',
      'Pasighat',
      'Roing',
      'Seppa',
      'Tawang',
      'Tezu',
      'Ziro'
    ],

    'Manipur': [
      'Andro',
      'Bishnupur',
      'HerioK',
      'Imphal',
      'Jiribam',
      'Kakching',
      'Kakching Khunou',
      'Khongman',
      'Kumbi',
      'Kwakta',
      'Lamai',
      'Lamjaotongba',
      'Lamshang',
      'Lilong (Imphal West)',
      'Lilong (Thoubal)',
      'Mayang Imphal',
      'Moirang',
      'Moreh',
      'Nambol',
      'Naoriya Pakhanglakpa',
      'Ningthoukhong',
      'Oinam',
      'Porompat',
      'Samurou',
      'Sekmai Bazar',
      'Sikhong Sekmai',
      'Sugnu',
      'Thongkhong Laxmi Bazar',
      'Thoubal',
      'Torban (Khetri Leikai)',
      'Wangjing',
      'Wangoi',
      'Yairipok'
    ],

    'Meghalaya': [
      'Baghmara',
      'Cherapunjee',
      'Jawai',
      'Madanrting',
      'Mairang',
      'Mawlai',
      'Nongmynsong',
      'Nongpoh',
      'Nongstoin',
      'Nongthymmai',
      'Pynthorumkhrah',
      'Resubelpara',
      'Shillong',
      'Shillong Cantt.',
      'Tura',
      'Williamnagar'
    ],

    'Mizoram': [
      'Aizawl',
      'Bairabi',
      'Biate',
      'Champhai',
      'Darlawn',
      'Hnahthial',
      'Khawhai',
      'Khawzawl',
      'Kolasib',
      'Lengpui',
      'Lunglei',
      'Mamit',
      'N. Vanlaiphai',
      'N. Kawnpui',
      'Saiha',
      'Sairang',
      'Saitual',
      'Serchhip',
      'Thenzawl',
      'Tlabung',
      'Vairengte',
      'Zawlnuam'
    ],

    'Nagaland': [
      'Chumukedima',
      'Dimapur',
      'Kohima',
      'Mokokchung',
      'Mon',
      'Phek',
      'Tuensang',
      'Wokha',
      'Zunheboto'
    ],

    'Sikkim': [
      'Gangtok',
      'Gyalshing',
      'Jorethang',
      'Mangan',
      'Namchi',
      'Nayabazar',
      'Rangpo',
      'Singtam',
      'Upper Tadong'
    ],

    'Tripura': [
      'Agartala',
      'Amarpur',
      'Ambassa',
      'Badharghat',
      'Belonia',
      'Dharmanagar',
      'Gakulnagar',
      'Gandhigram',
      'Indranagar',
      'Jogendranagar',
      'Kailasahar',
      'Kamalpur',
      'Kanchanpur',
      'Khowai',
      'Kumarghat',
      'Kunjaban',
      'Narsingarh',
      'Pratapgarh',
      'Ranirbazar',
      'Sabroom',
      'Sonamura',
      'Teliamura',
      'Udaipur'
    ],
  };
}
